Repository puppeteer/puppeteer, pull requests merged in 2019-10, with the labels that each got.

#5045 chore: drop Node.js v6 support
  .appveyor.yml
  .ci/node6/Dockerfile.linux
  .cirrus.yml
  .travis.yml
  DeviceDescriptors.js
  Errors.js
  README.md
  experimental/puppeteer-firefox/DeviceDescriptors.js
  experimental/puppeteer-firefox/lib/Page.js
  experimental/puppeteer-firefox/lib/helper.js
  experimental/puppeteer-firefox/misc/install-preferences.js
  index.js
  install.js
  lib/BrowserFetcher.js
  lib/Page.js
  lib/helper.js
  package.json
  test/evaluation.spec.js
  test/headful.spec.js
  test/launcher.spec.js
  utils/doclint/Source.js
  utils/node6-transform/TransformAsyncFunctions.js
  utils/node6-transform/index.js
  utils/node6-transform/test/test.js
Labels: P1, breaking change, cla: yes, health

#5068 chore: use map instead of plain object
  lib/LifecycleWatcher.js
Labels: cla: yes

#5012 feat(api): add page.emulateMedia{Type,Features}
  docs/api.md
  experimental/puppeteer-firefox/lib/Page.js
  lib/Page.js
  test/emulation.spec.js
  test/test.js
Labels: breaking change, cla: yes, feature

#4949 feat(api): add page.emulateTimezone(timezoneId)
  docs/api.md
  lib/Page.js
  test/emulation.spec.js
Labels: cla: yes, feature

#5021 docs: page.waitFor options object defination
  docs/api.md
  lib/Page.js
Labels: cla: yes

#5079 test: add page.screenshot viewport clipping test
  test/golden-chromium/screenshot-offscreen-clip.png
  test/golden-firefox/screenshot-offscreen-clip.png
  test/screenshot.spec.js
Labels: cla: yes

#5078 chore: mark version v2.0.0
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#5089 docs(api.md): use async/await instead of then
  docs/api.md
Labels: cla: yes
