Repository puppeteer/puppeteer, pull requests merged in 2020-10, with the labels that each got.

#6458 feat(chromium) roll Chromium to r809590
  new-docs/puppeteer.browsercontext.overridepermissions.md
  new-docs/puppeteer.protocol.accessibility.md
  new-docs/puppeteer.protocol.accessibility.queryaxtreerequest.accessiblename.md
  new-docs/puppeteer.protocol.accessibility.queryaxtreerequest.backendnodeid.md
  new-docs/puppeteer.protocol.accessibility.queryaxtreerequest.md
  new-docs/puppeteer.protocol.accessibility.queryaxtreerequest.nodeid.md
  new-docs/puppeteer.protocol.accessibility.queryaxtreerequest.objectid.md
  new-docs/puppeteer.protocol.accessibility.queryaxtreerequest.role.md
  new-docs/puppeteer.protocol.accessibility.queryaxtreeresponse.md
  new-docs/puppeteer.protocol.accessibility.queryaxtreeresponse.nodes.md
  new-docs/puppeteer.protocol.browser.permissiondescriptor.md
  new-docs/puppeteer.protocol.browser.permissiondescriptor.type.md
  new-docs/puppeteer.protocol.css.cssstylesheetheader.isconstructed.md
  new-docs/puppeteer.protocol.css.cssstylesheetheader.ismutable.md
  new-docs/puppeteer.protocol.css.cssstylesheetheader.md
  new-docs/puppeteer.protocol.network.crossoriginembedderpolicystatus.md
  new-docs/puppeteer.protocol.network.crossoriginembedderpolicystatus.reportingendpoint.md
  new-docs/puppeteer.protocol.network.crossoriginembedderpolicystatus.reportonlyreportingendpoint.md
  new-docs/puppeteer.protocol.network.crossoriginembedderpolicystatus.reportonlyvalue.md
  new-docs/puppeteer.protocol.network.crossoriginopenerpolicystatus.md
  new-docs/puppeteer.protocol.network.crossoriginopenerpolicystatus.reportingendpoint.md
  new-docs/puppeteer.protocol.network.crossoriginopenerpolicystatus.reportonlyreportingendpoint.md
  new-docs/puppeteer.protocol.network.crossoriginopenerpolicystatus.reportonlyvalue.md
  new-docs/puppeteer.protocol.network.md
  new-docs/puppeteer.protocol.network.setattachdebugheaderrequest.enabled.md
  new-docs/puppeteer.protocol.network.setattachdebugheaderrequest.md
  new-docs/puppeteer.protocol.overlay.gridhighlightconfig.gridbackgroundcolor.md
  new-docs/puppeteer.protocol.overlay.gridhighlightconfig.md
  new-docs/puppeteer.protocol.profiler.getcountersresponse.md
  new-docs/puppeteer.protocol.profiler.getcountersresponse.result.md
  new-docs/puppeteer.protocol.profiler.getruntimecallstatsresponse.md
  new-docs/puppeteer.protocol.profiler.getruntimecallstatsresponse.result.md
  new-docs/puppeteer.protocol.profiler.md
  new-docs/puppeteer.protocol.profiler.runtimecallcounterinfo.md
  new-docs/puppeteer.protocol.profiler.runtimecallcounterinfo.name.md
  new-docs/puppeteer.protocol.profiler.runtimecallcounterinfo.time.md
  new-docs/puppeteer.protocol.profiler.runtimecallcounterinfo.value.md
  new-docs/puppeteer.protocol.webaudio.audiolistener.md
  new-docs/puppeteer.protocol.webaudio.md
  package.json
  src/common/Browser.ts
  src/revisions.ts
  test/idle_override.spec.ts
  test/page.spec.ts
Labels: cla: yes

#6471 docs(examples): update selector for search example
  examples/search.js
  experimental/puppeteer-firefox/examples/search.js
Labels: cla: yes

#6465 fix: update preferences in default Firefox profile
  src/node/Launcher.ts
  test/waittask.spec.ts
Labels: cla: yes

#6459 feat(a11y-query): add aria query handler (without waitFor support)
  src/common/AriaQueryHandler.ts
  src/common/QueryHandler.ts
  test/ariaqueryhandler.spec.ts
Labels: cla: yes

#6475 fix(queryhandler) only expose custom handlers
  src/common/QueryHandler.ts
Labels: cla: yes

#6476 docs(queryhandler): add custom query handler docs
  new-docs/puppeteer.customqueryhandler.md
  new-docs/puppeteer.customqueryhandler.queryall.md
  new-docs/puppeteer.customqueryhandler.queryone.md
  new-docs/puppeteer.md
  new-docs/puppeteer.puppeteer.__experimental_clearqueryhandlers.md
  new-docs/puppeteer.puppeteer.__experimental_customqueryhandlernames.md
  new-docs/puppeteer.puppeteer.__experimental_registercustomqueryhandler.md
  new-docs/puppeteer.puppeteer.__experimental_unregistercustomqueryhandler.md
  new-docs/puppeteer.puppeteer.md
  src/api-docs-entry.ts
  src/common/Puppeteer.ts
  src/common/QueryHandler.ts
Labels: cla: yes

#6472 feat(a11y-query): extend aria handler with waitFor
  src/common/AriaQueryHandler.ts
  src/common/DOMWorld.ts
  src/common/ExecutionContext.ts
  src/common/Page.ts
  src/common/helper.ts
  test/ariaqueryhandler.spec.ts
  test/frame.spec.ts
Labels: cla: yes

#6477 chore(agnostify): Create Node and Web initializer.
  src/common/Puppeteer.ts
  src/index-core.ts
  src/index.ts
  src/initialize-node.ts
  src/initialize-web.ts
Labels: agnostification, cla: yes

#6483 chore: enforce Conventional Commits through commitlint
  CONTRIBUTING.md
  commitlint.config.js
  package.json
Labels: cla: yes

#6488 chore: bump misc dependencies
  package.json
Labels: cla: yes

#6490 chore(node): move install.ts into node/
  install.js
  src/node/install.ts
Labels: agnostification, cla: yes

#6487 chore: update eslint & eslint plugins
  .eslintrc.js
  new-docs/puppeteer.frame.waitfor.md
  new-docs/puppeteer.jshandle.jsonvalue.md
  new-docs/puppeteer.puppeteer.launch.md
  package.json
  src/.eslintrc.js
  src/common/Connection.ts
  src/common/FrameManager.ts
  src/common/JSHandle.ts
  src/common/Puppeteer.ts
  test/CDPSession.spec.ts
  test/elementhandle.spec.ts
  test/keyboard.spec.ts
  test/launcher.spec.ts
  test/mocha-utils.ts
  test/navigation.spec.ts
  test/network.spec.ts
  test/page.spec.ts
  test/waittask.spec.ts
Labels: cla: yes

#6509 feat(queryhandler): add built-in pierce handler
  src/common/QueryHandler.ts
  test/queryselector.spec.ts
Labels: cla: yes

#6506 fix(launcher): also support relative userDataDir on headless Windows
  src/node/Launcher.ts
  test/launcher.spec.ts
Labels: cla: yes

#6515 chore(agnostification): common/helper.ts
  .travis.yml
  package.json
  src/common/helper.ts
Labels: cla: yes

#6520 chore(agnostification): agnostify web socket connections
  src/common/BrowserConnector.ts
  src/common/BrowserWebSocketTransport.ts
  src/node/BrowserRunner.ts
  src/node/NodeWebSocketTransport.ts
  test-browser/connection.spec.js
  test-browser/helper.js
  web-test-runner.config.js
Labels: agnostification, cla: yes

#6522 fix(utils): typo fix
  utils/apply_next_version.js
Labels: cla: yes

#6537 chore: fix travis config
  .travis.yml
  mocha-config/puppeteer-unit-tests.js
  package.json
Labels: cla: yes, do not merge yet

#6538 fix: ignore spurious bindingCalled events
  src/common/DOMWorld.ts
  src/common/Page.ts
Labels: cla: yes

#6536 chore: automate publishing on new Git tags
  .github/workflows/publish-on-tag.yml
  .npmrc
  CONTRIBUTING.md
  package.json
Labels: cla: yes

#6542 chore: mark version v5.4.0
  README.md
  docs/api.md
  package.json
  src/common/Puppeteer.ts
  src/common/QueryHandler.ts
  test/elementhandle.spec.ts
  test/queryselector.spec.ts
Labels: cla: yes

#6544 chore: bump version to v5.4.0-post
  docs/api.md
  package.json
Labels: cla: yes

#6543 docs(queryhandler): fix link
  docs/api.md
Labels: cla: yes

#6550 chore: run unit tests on node 10.15 + fix fs.promises access
  .travis.yml
  src/common/DOMWorld.ts
  src/common/JSHandle.ts
  src/common/Page.ts
  src/common/helper.ts
Labels: agnostification, cla: yes

#6529 Update troubleshooting.md
  docs/troubleshooting.md
Labels: cla: yes

#6552 chore: mark version 5.4.1
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#6553 chore: mark v5.4.1-post
  docs/api.md
  package.json
Labels: cla: yes

#6556 chore: automate versioning + changelog
  .versionrc
  CHANGELOG.md
  CONTRIBUTING.md
  commitlint.config.js
  package.json
Labels: cla: yes

#6557 docs(api): expand registerCustomQueryHandler example
  docs/api.md
Labels: cla: yes

#6558 chore: automate Chromium => Puppeteer version listing
  CONTRIBUTING.md
  docs/api.md
  utils/doclint/cli.js
  utils/doclint/preprocessor/index.js
  versions.js
Labels: cla: yes
