Repository puppeteer/puppeteer, pull requests merged in 2020-05, with the labels that each got.

#5807 docs(api.md): emulateMediaFeatures few tidy updates
  docs/api.md
Labels: cla: yes

#5799 Add text highlight for Javascript on debugging section
  README.md
Labels: cla: yes

#5789 chore: migrate src/Puppeteer to TypeScript
  index.js
  src/Browser.ts
  src/BrowserFetcher.ts
  src/DeviceDescriptors.ts
  src/Errors.ts
  src/Launcher.ts
  src/Puppeteer.js
  src/Puppeteer.ts
  src/api.js
  src/externs.d.ts
  test/launcher.spec.js
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#5808 chore: migrate src/api.js to TypeScript
  src/api.ts
Labels: cla: yes, typescript-migration

#5805 chore: improve readability for path strings
  utils/protocol-types-generator/index.js
Labels: cla: yes

#5809 chore: migrate src/Page.js to TypeScript
  src/Browser.ts
  src/Dialog.ts
  src/FrameManager.ts
  src/JSHandle.ts
  src/NetworkManager.ts
  src/Page.ts
  src/Target.ts
  src/externs.d.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes, typescript-migration

#5811 chore: remove src/externs.d.ts
  package.json
  src/Browser.ts
  src/Connection.ts
  src/ConnectionTransport.ts
  src/EmulationManager.ts
  src/Launcher.ts
  src/Page.ts
  src/PipeTransport.ts
  src/Puppeteer.ts
  src/PuppeteerViewport.ts
  src/Target.ts
  src/WebSocketTransport.ts
  src/externs.d.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#5813 chore: mark version v3.0.3
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#5814 chore: bump version to 3.0.3-post
  docs/api.md
  package.json
Labels: cla: yes

#5816 fix: remove node@14 specific extract timeout
  src/BrowserFetcher.ts
Labels: cla: yes

#5821 chore: add Node.js 12 & 14 to CI
  .travis.yml
Labels: cla: yes

#5819 chore: remove unused mime-types dependency
  package.json
Labels: cla: yes

#5823 chore: mark version v3.0.4
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#5824 chore: mark v3.0.4-post
  docs/api.md
  package.json
Labels: cla: yes

#5826 chore: remove src/TaskQueue
  src/Browser.ts
  src/JSHandle.ts
  src/Page.ts
  src/Target.ts
  src/TaskQueue.ts
Labels: cla: yes

#5829 chore: Add command to run eslint with `--fix` flag
  CONTRIBUTING.md
  package.json
Labels: cla: yes

#5827 feat: add more options to check_availability script
  utils/check_availability.js
Labels: cla: yes

#5832 chore: private-ise src/Accessibility.ts
  src/Accessibility.ts
Labels: cla: yes

#5831 chore: add @types/proxy-from-env
  package.json
Labels: cla: yes

#5845 Warn when given unsupported product name.
  package.json
  src/Launcher.ts
  test/launcher.spec.js
  test/mocha-utils.js
Labels: cla: yes

#5850 chore: extract `BrowserRunner` into its own module
  src/Launcher.ts
  src/Puppeteer.ts
  src/launcher/BrowserRunner.ts
  src/launcher/LaunchOptions.ts
  utils/doclint/Source.js
  utils/doclint/cli.js
Labels: cla: yes, typescript-migration

#5852 chore: add running TSC to test README
  test/README.md
Labels: cla: yes

#5858 chore: extract `SecurityDetails` into its own module
  src/NetworkManager.ts
  src/SecurityDetails.ts
  src/api.ts
Labels: cla: yes

#5860 chore: upgrade TypeScript to 3.9
  package.json
Labels: cla: yes

#5862 chore: force Mocha to exit on CI
  mocha-config/base.js
Labels: cla: yes

#5856 chore: extract `ConsoleMessage` and `FileChooser` into its own module
  src/ConsoleMessage.ts
  src/FileChooser.ts
  src/Page.ts
  src/api.ts
Labels: cla: yes

#5864 chore: fetch Firefox from json source instead of run a RegExp
  install.js
  src/BrowserFetcher.ts
  test/launcher.spec.js
Labels: cla: yes, firefox

#5861 chore: extract `Request` and `Response` into its own module
  src/FrameManager.ts
  src/LifecycleWatcher.ts
  src/NetworkManager.ts
  src/Page.ts
  src/Request.ts
  src/Response.ts
  src/api.ts
Labels: cla: yes

#5868 chore: restore page.setUserAgent test
  test/page.spec.js
Labels: cla: yes

#5859 chore: Fix async dialog specs when they fail
  test/dialog.spec.js
Labels: cla: yes

#5875 docs(examples): Add cucumber-puppeteer-example for integration testing
  examples/README.md
Labels: cla: yes

#5878 docs(contributing): clarify list of Chromium versions
  CONTRIBUTING.md
  docs/api.md
Labels: cla: yes

#5879 feat(chromium): roll Chromium to r756035
  package.json
  src/protocol.d.ts
  test/cookies.spec.js
Labels: cla: yes

#5883 chore: mark version v3.1.0
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#5884 chore: bump version to v3.1.0-post
  docs/api.md
  package.json
Labels: cla: yes

#5682 Fix: support async functions as an argument for waitForFunction
  docs/api.md
  src/DOMWorld.ts
  test/waittask.spec.js
Labels: cla: yes

#5863 chore: Error if coverage couldn't find the given class
  test/coverage-utils.js
Labels: cla: yes

#5903 chore: update Travis to run latest macOS and fix HTTPS test
  .travis.yml
  test/navigation.spec.js
Labels: cla: yes

#5899 chore: stop Protocol types being globally available
  src/Accessibility.ts
  src/Browser.ts
  src/Connection.ts
  src/Coverage.ts
  src/EmulationManager.ts
  src/ExecutionContext.ts
  src/FileChooser.ts
  src/FrameManager.ts
  src/JSHandle.ts
  src/NetworkManager.ts
  src/Page.ts
  src/Request.ts
  src/Response.ts
  src/SecurityDetails.ts
  src/Target.ts
  src/Worker.ts
  src/helper.ts
  src/protocol.d.ts
  utils/protocol-types-generator/index.js
Labels: cla: yes

#5473 Don't use expect within Promises (#5466)
  src/protocol.d.ts
  test/dialog.spec.js
  test/navigation.spec.js
Labels: cla: yes, firefox

#5920 chore: Fix undefined `rm` in mocha-utils
  test/mocha-utils.js
Labels: cla: yes

#5901 feat(api): add page.emulateVisionDeficiency(type)
  docs/api.md
  src/Page.ts
  test/emulation.spec.js
  test/golden-chromium/vision-deficiency-achromatopsia.png
  test/golden-chromium/vision-deficiency-blurredVision.png
  test/golden-chromium/vision-deficiency-deuteranopia.png
  test/golden-chromium/vision-deficiency-protanopia.png
  test/golden-chromium/vision-deficiency-tritanopia.png
  utils/doclint/check_public_api/index.js
Labels: cla: yes, feature

#5932 chore: remove doclint generate_types code
  .gitignore
  .travis.yml
  package.json
  utils/doclint/generate_types/index.js
  utils/doclint/generate_types/test/test.ts
  utils/doclint/generate_types/test/tsconfig.json
Labels: cla: yes

#5934 chore: rename Request class to HTTPRequest
  docs/api.md
  src/HTTPRequest.ts
  src/LifecycleWatcher.ts
  src/NetworkManager.ts
  src/Page.ts
  src/Response.ts
  src/api.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#5905 feat: recognize webviews as regular pages
  src/Target.ts
Labels: cla: yes

#5907 Use Mitt as the Event Emitter
  docs/api.md
  package.json
  src/Browser.ts
  src/BrowserFetcher.ts
  src/Connection.ts
  src/EventEmitter.ts
  src/FrameManager.ts
  src/NetworkManager.ts
  src/Page.ts
  src/WebSocketTransport.ts
  src/Worker.ts
  src/api.ts
  src/helper.ts
  src/launcher/BrowserRunner.ts
  tsconfig.json
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#5937 chore: Mark version v3.2.0
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#5938 chore: bump version to v3.2.0-post
  docs/api.md
  package.json
Labels: cla: yes

#5940 chore: rename `Response` to `HTTPResponse`
  docs/api.md
  src/FrameManager.ts
  src/HTTPRequest.ts
  src/HTTPResponse.ts
  src/LifecycleWatcher.ts
  src/NetworkManager.ts
  src/Page.ts
  src/api.ts
Labels: cla: yes

#5942 chore: update request and response references in docs
  docs/api.md
Labels: cla: yes

#5941 chore: rename Worker to WebWorker
  docs/api.md
  src/Page.ts
  src/Target.ts
  src/WebWorker.ts
  src/api.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes
