Repository puppeteer/puppeteer, pull requests merged in 2020-04, with the labels that each got.

#5566 chore: Upgrade TypeScript to 3.8
  package.json
Labels: cla: yes

#5572 docs: connect works with any supported browser
  docs/api.md
Labels: cla: yes

#5568 chore: Move source files into src/ and emit to lib/ with TypeScript
  .eslintignore
  .gitignore
  .npmignore
  install.js
  package.json
  src/.eslintrc.js
  src/Accessibility.js
  src/Browser.js
  src/BrowserFetcher.js
  src/Connection.js
  src/Coverage.js
  src/DOMWorld.js
  src/DeviceDescriptors.js
  src/Dialog.js
  src/EmulationManager.js
  src/Errors.js
  src/Events.js
  src/ExecutionContext.js
  src/FrameManager.js
  src/Input.js
  src/JSHandle.js
  src/Launcher.js
  src/LifecycleWatcher.js
  src/Multimap.js
  src/NetworkManager.js
  src/Page.js
  src/PipeTransport.js
  src/Puppeteer.js
  src/Target.js
  src/TaskQueue.js
  src/TimeoutSettings.js
  src/Tracing.js
  src/USKeyboardLayout.js
  src/WebSocketTransport.js
  src/Worker.js
  src/api.js
  src/externs.d.ts
  src/helper.js
  src/protocol.d.ts
  tsconfig.json
  utils/protocol-types-generator/index.js
Labels: cla: yes

#5580 chore: Remove travis-autodeploy
  .travis.yml
Labels: cla: yes

#5576 Fix link to source files in documentation
  docs/api.md
Labels: cla: yes

#5582 Run chromium on node 12 on travis
  .travis.yml
Labels: cla: yes

#5581 chore: Use expect for assertions
  index.js
  package.json
  src/Page.js
  test/puppeteer.spec.js
  test/target.spec.js
  test/utils.js
  utils/browser/test.js
  utils/doclint/check_public_api/test/test.js
  utils/doclint/preprocessor/test.js
  utils/testrunner/Matchers.js
  utils/testrunner/README.md
  utils/testrunner/examples/fail.js
  utils/testrunner/examples/hookfail.js
  utils/testrunner/examples/hooktimeout.js
  utils/testrunner/index.js
  utils/testrunner/test/test.js
Labels: cla: yes

#5502 docs(puppeteer-firefox): Add deprecation warning to README
  experimental/puppeteer-firefox/README.md
Labels: cla: yes

#5585 docs: Fix simple typo, existance -> existence
  test/utils.js
  utils/flakiness-dashboard/FlakinessDashboard.js
Labels: cla: yes

#5589 docs - Replaced Invalid Device Descriptors link
  docs/api.md
Labels: cla: yes

#5591 chore: Fix missed `src/` vs `lib/` documentation
  CONTRIBUTING.md
  docs/api.md
  package.json
  utils/doclint/README.md
Labels: cla: yes

#5575 chore: Skip failing cookie tests in Firefox
  test/cookies.spec.js
  test/defaultbrowsercontext.spec.js
Labels: cla: yes

#5584 chore: Fix Page.emulateMedia doclint failure
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#5592 chore: Remove flakiness dashboard
  .appveyor.yml
  .cirrus.yml
  .travis.yml
  test/test.js
  test/utils.js
  utils/flakiness-dashboard/FlakinessDashboard.js
  utils/flakiness-dashboard/index.js
Labels: cla: yes

#5594 chore: Fix DocLint method diffing
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#5606 changed .pdf part of api
  docs/api.md
Labels: cla: no

#5607 fixed api emulateMedia the right way
  docs/api.md
Labels: cla: yes

#5583 Trim CI down whilst we get it stable
  .appveyor.yml
  .cirrus.yml
  .travis.yml
  travis/chromium.sh
Labels: cla: yes

#5608 Add Firefox back to Travis
  .travis.yml
  utils/browser/test.js
Labels: cla: yes

#5600 Migrate unit tests to Mocha
  .eslintrc.js
  .mocharc.js
  package.json
  test/CDPSession.spec.js
  test/README.md
  test/accessibility.spec.js
  test/browser.spec.js
  test/browsercontext.spec.js
  test/chromiumonly.spec.js
  test/click.spec.js
  test/cookies.spec.js
  test/coverage-utils.js
  test/coverage.spec.js
  test/defaultbrowsercontext.spec.js
  test/dialog.spec.js
  test/elementhandle.spec.js
  test/emulation.spec.js
  test/evaluation.spec.js
  test/fixtures.spec.js
  test/frame.spec.js
  test/headful.spec.js
  test/ignorehttpserrors.spec.js
  test/input.spec.js
  test/jshandle.spec.js
  test/keyboard.spec.js
  test/launcher.spec.js
  test/mocha-utils.js
  test/mouse.spec.js
  test/navigation.spec.js
  test/network.spec.js
  test/oopif.spec.js
  test/page.spec.js
  test/puppeteer.spec.js
  test/queryselector.spec.js
  test/requestinterception.spec.js
  test/screenshot.spec.js
  test/target.spec.js
  test/test.js
  test/touchscreen.spec.js
  test/tracing.spec.js
  test/utils.js
  test/waittask.spec.js
  test/worker.spec.js
Labels: cla: yes

#5616 chore: Migrate remaining tests to Mocha
  .eslintignore
  CONTRIBUTING.md
  mocha-config/base.js
  mocha-config/browser-bundle-tests.js
  mocha-config/doclint-tests.js
  mocha-config/puppeteer-unit-tests.js
  package.json
  test/README.md
  utils/browser/browser.spec.js
  utils/doclint/check_public_api/test/public-api.spec.js
  utils/doclint/check_public_api/test/test.js
  utils/doclint/preprocessor/preprocessor.spec.js
  utils/doclint/preprocessor/test.js
  utils/testrunner/.npmignore
  utils/testrunner/LICENSE
  utils/testrunner/Multimap.js
  utils/testrunner/README.md
  utils/testrunner/Reporter.js
  utils/testrunner/TestRunner.js
  utils/testrunner/examples/fail.js
  utils/testrunner/examples/hookfail.js
  utils/testrunner/examples/hooktimeout.js
  utils/testrunner/examples/timeout.js
  utils/testrunner/examples/unhandledpromiserejection.js
  utils/testrunner/index.js
  utils/testrunner/package.json
  utils/testrunner/test/test.js
  utils/testrunner/test/testrunner.spec.js
Labels: cla: yes

#5610 chore(deps): update extract-zip to version 2
  experimental/puppeteer-firefox/lib/BrowserFetcher.js
  package.json
  src/BrowserFetcher.js
  tsconfig.json
Labels: cla: yes

#5595 feat(TypeScript): Move DeviceDescriptors to TS
  src/DeviceDescriptors.ts
  tsconfig.json
  utils/doclint/cli.js
Labels: cla: yes, typescript-migration

#5635 chore(eslint): Add ESLint TypeScript linting
  .eslintignore
  .eslintrc.js
  package.json
  src/DeviceDescriptors.ts
Labels: cla: yes

#5638 chore: update ws library
  package.json
Labels: cla: yes

#5640 fix: Update preferred revision after Launcher is created
  docs/api.md
  examples/cross-browser.js
  src/Puppeteer.js
Labels: cla: yes

#5643 fix: set revision based on PUPPETEER_PRODUCT
  .travis.yml
  index.js
  src/Launcher.js
  src/Puppeteer.js
  test/launcher.spec.js
  test/mocha-utils.js
Labels: cla: yes

#5634 docs(readme): update cross-browser FAQ
  README.md
Labels: cla: yes

#5642 chore: mark version v3.0.0
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#5649 chore: bump version to v3.0.0-post
  docs/api.md
  package.json
Labels: cla: yes

#5650 docs(contributing): update npm dist tags section
  CONTRIBUTING.md
Labels: cla: yes

#5652 chore: Log reminder about tsc if DocLint fails locally
  utils/doclint/cli.js
Labels: cla: yes

#5639 Migrate src/Dialog to TypeScript
  .eslintrc.js
  src/Dialog.ts
  utils/doclint/check_public_api/JSBuilder.js
  utils/doclint/cli.js
Labels: cla: yes, typescript-migration

#5655 fix(JSHandle): Fixes file upload
  src/JSHandle.js
  test/input.spec.js
Labels: cla: yes, fileupload

#5667 docs(troubleshooting): list libgbm-dev dependency
  docs/troubleshooting.md
Labels: cla: yes

#5669 chore: Fix installing from GitHub URL
  install.js
  package.json
  typescript-if-required.js
Labels: cla: yes

#5666 docs: Change the Alpine Docker example to use env instead of launch option
  docs/troubleshooting.md
Labels: cla: yes

#5659 chore: manage published files via `files` option
  .npmignore
  package.json
Labels: cla: yes

#5658 chore: Migrate TaskQueue to TypeScript
  .eslintrc.js
  src/Page.js
  src/Target.js
  src/TaskQueue.js
  src/TaskQueue.ts
  src/externs.d.ts
Labels: cla: yes, typescript-migration

#5657 chore: Update CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: cla: yes

#5637 chore(ci): re-enable tests on Windows
  .travis.yml
  mocha-config/puppeteer-unit-tests.js
  test/headful.spec.js
  test/launcher.spec.js
  test/mocha-utils.js
  test/network.spec.js
Labels: cla: yes

#5683 docs: Fix DeviceDescriptor leading to 404
  docs/api.md
Labels: cla: yes

#5691 chore: migrate `src/timeoutsettings` to typescript
  src/DOMWorld.js
  src/FrameManager.js
  src/TimeoutSettings.ts
  src/externs.d.ts
Labels: cla: yes, typescript-migration

#5690 chore: delete `src/multimap.js`
  src/Multimap.js
Labels: cla: yes

#5689 Migrate src/helper to TypeScript
  src/helper.js
  src/helper.ts
  src/promisify.ts
Labels: cla: yes, typescript-migration

#5692 chore: migrate `src/pipetransport` to typescript
  src/Launcher.js
  src/PipeTransport.ts
  src/helper.ts
  src/types.d.ts
Labels: cla: yes, typescript-migration

#5693 chore(docker): Add missing chromium dependency
  .ci/node10/Dockerfile.linux
  .ci/node12/Dockerfile.linux
  docs/troubleshooting.md
Labels: cla: yes

#5696 chore: Migrate src/WebSocketTransport to TypeScript
  src/Launcher.js
  src/WebSocketTransport.ts
Labels: cla: yes

#5694 chore: migrate `src/Connection` to TypeScript
  .eslintrc.js
  src/Accessibility.js
  src/Browser.js
  src/Connection.ts
  src/Coverage.js
  src/Dialog.ts
  src/EmulationManager.js
  src/ExecutionContext.js
  src/FrameManager.js
  src/Input.js
  src/JSHandle.js
  src/NetworkManager.js
  src/Page.js
  src/Target.js
  src/Tracing.js
  src/Worker.js
  src/externs.d.ts
  src/helper.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes, typescript-migration

#5695 chore: migrate `src/USKeyboardLayout` to typescript
  .travis.yml
  src/Input.js
  src/USKeyboardLayout.ts
Labels: cla: yes, typescript-migration

#5699 chore: migrate src/helpers.ts to ESM
  src/Connection.ts
  src/Dialog.ts
  src/PipeTransport.ts
  src/helper.ts
  src/types.d.ts
Labels: cla: yes, typescript-migration

#5700 chore: enforce spacing around braces
  .eslintrc.js
  install.js
  package.json
  src/Browser.js
  src/Coverage.js
  src/EmulationManager.js
  src/Events.js
  src/ExecutionContext.js
  src/FrameManager.js
  src/Input.js
  src/JSHandle.js
  src/Launcher.js
  src/NetworkManager.js
  src/Page.js
  src/Target.js
  src/TaskQueue.ts
  src/helper.ts
  test/CDPSession.spec.js
  test/accessibility.spec.js
  test/browser.spec.js
  test/browsercontext.spec.js
  test/chromiumonly.spec.js
  test/click.spec.js
  test/cookies.spec.js
  test/coverage.spec.js
  test/defaultbrowsercontext.spec.js
  test/dialog.spec.js
  test/elementhandle.spec.js
  test/emulation.spec.js
  test/evaluation.spec.js
  test/fixtures.spec.js
  test/frame.spec.js
  test/golden-utils.js
  test/headful.spec.js
  test/ignorehttpserrors.spec.js
  test/input.spec.js
  test/jshandle.spec.js
  test/keyboard.spec.js
  test/launcher.spec.js
  test/mouse.spec.js
  test/navigation.spec.js
  test/network.spec.js
  test/oopif.spec.js
  test/page.spec.js
  test/queryselector.spec.js
  test/requestinterception.spec.js
  test/screenshot.spec.js
  test/target.spec.js
  test/tracing.spec.js
  test/waittask.spec.js
  test/worker.spec.js
  utils/doclint/check_public_api/MDBuilder.js
  utils/doclint/check_public_api/index.js
  utils/fetch_devices.js
  utils/testserver/index.js
Labels: cla: yes

#5702 chore: migrate src/coverage to TypeScript
  src/Coverage.ts
Labels: cla: yes, typescript-migration

#5703 chore: migrate src/JSHandle to TS
  src/Accessibility.js
  src/DOMWorld.js
  src/ExecutionContext.js
  src/FrameManager.js
  src/JSHandle.ts
  src/Page.js
  src/externs.d.ts
  utils/doclint/check_public_api/JSBuilder.js
Labels: cla: yes, typescript-migration

#5706 Fix `USKeyboardLayout` relative url
  docs/api.md
Labels: cla: yes

#5705 chore: migrate src/ExecutionContext
  .eslintrc.js
  src/DOMWorld.js
  src/ExecutionContext.ts
  src/JSHandle.ts
  src/externs.d.ts
  src/helper.ts
Labels: cla: yes, typescript-migration

#5709 chore: mark version v3.0.1
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#5712 chore: add `install.js` to `files` for publishing
  package.json
Labels: cla: yes

#5714 chore: add test for npm package installing correctly
  .travis.yml
  package.json
  scripts/test-install.sh
Labels: cla: yes

#5715 chore: migrate src/Worker to typescript
  src/Worker.ts
Labels: cla: yes, typescript-migration

#5708 macOS on Travis
  .travis.yml
Labels: cla: yes

#5717 chore: bump version to 3.0.1-post
  docs/api.md
  package.json
Labels: cla: yes

#5716 Clean travis.yml and docs
  .travis.yml
  docs/troubleshooting.md
Labels: cla: yes

#5676 Update pngjs to 5.0.0 and jpeg-js to 0.3.7
  package.json
Labels: cla: yes

#5721 Update clipboard read write permissions with CDP
  src/Browser.js
Labels: cla: yes

#5723 chore: migrate src/Tracing to TypeScript
  src/Page.js
  src/Tracing.ts
  src/api.js
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#5724 chore: migrate src/Events to TypeScript
  src/Events.ts
Labels: cla: yes

#5725 chore: migrate src/Errors to TypeScript
  src/Errors.ts
Labels: cla: yes, typescript-migration

#5726 chore: migrate src/Accessibility to TypeScript
  src/Accessibility.ts
  test/headful.spec.js
Labels: cla: yes, typescript-migration

#5727 chore: migrate src/BrowserFetcher to TypeScript
  docs/api.md
  src/BrowserFetcher.ts
  src/Launcher.js
  src/Puppeteer.js
  src/api.js
Labels: cla: yes, typescript-migration

#5733 fix: make uploadFile throw for non-existent files
  src/JSHandle.ts
  test/input.spec.js
Labels: cla: yes

#5734 chore: migrate src/LifecycleWatcher
  docs/api.md
  src/DOMWorld.js
  src/FrameManager.js
  src/LifecycleWatcher.ts
  src/Page.js
  src/externs.d.ts
  utils/doclint/check_public_api/index.js
  utils/doclint/generate_types/index.js
Labels: cla: yes, typescript-migration

#5750 chore: remove puppeteer-web
  index.js
  mocha-config/browser-bundle-tests.js
  package.json
  travis/chromium.sh
  utils/browser/README.md
  utils/browser/WebSocket.js
  utils/browser/browser.spec.js
Labels: cla: yes

#5749 chore: split out CI into unit tests + extra checks
  .travis.yml
Labels: cla: yes

#5732 chore: log useful error for Node v14 breakage
  src/BrowserFetcher.ts
Labels: cla: yes

#5748 chore: use Node's promisify function
  src/helper.ts
  src/promisify.ts
Labels: cla: yes

#5751 chore: small CI tidy ups
  .travis.yml
  mocha-config/puppeteer-unit-tests.js
Labels: cla: yes

#5752 chore: mark version v3.0.2
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#5759 chore: bump version to 3.0.2-post
  docs/api.md
  package.json
Labels: cla: yes

#5760 chore: update protocol.d.ts
  src/protocol.d.ts
Labels: cla: yes

#5761 chore: migrate src/Browser to TS
  src/Browser.js
  src/Browser.ts
  src/Connection.ts
  src/Page.js
  src/Puppeteer.js
  src/Target.js
  src/TaskQueue.ts
  src/externs.d.ts
  test/oopif.spec.js
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#5762 chore: enforce src/protocol.d.ts is in sync
  .travis.yml
  package.json
  utils/protocol-types-generator/index.js
Labels: cla: yes

#5763 chore: enforce naming of errors in catch blocks
  .eslintrc.js
  package.json
  src/BrowserFetcher.ts
  src/Coverage.ts
  src/DOMWorld.js
  src/ExecutionContext.ts
  src/Launcher.js
  src/Page.js
  src/helper.ts
  test/CDPSession.spec.js
  test/browsercontext.spec.js
  test/chromiumonly.spec.js
  test/click.spec.js
  test/cookies.spec.js
  test/elementhandle.spec.js
  test/emulation.spec.js
  test/evaluation.spec.js
  test/frame.spec.js
  test/headful.spec.js
  test/ignorehttpserrors.spec.js
  test/input.spec.js
  test/jshandle.spec.js
  test/keyboard.spec.js
  test/launcher.spec.js
  test/navigation.spec.js
  test/network.spec.js
  test/page.spec.js
  test/queryselector.spec.js
  test/requestinterception.spec.js
  test/screenshot.spec.js
  test/target.spec.js
  test/tracing.spec.js
  test/waittask.spec.js
  typescript-if-required.js
  utils/fetch_devices.js
Labels: cla: yes

#5765 chore: Enforce array type styles in TypeScript
  .eslintrc.js
  src/Accessibility.ts
Labels: cla: yes

#5764 chore: migrate src/DOMWorld to TypeScript
  src/DOMWorld.ts
  src/Input.ts
  src/LifecycleWatcher.ts
  src/TimeoutSettings.ts
Labels: cla: yes, typescript-migration

#5766 chore: migrate src/EmulationManager to TypeScript
  src/EmulationManager.ts
Labels: cla: yes

#5767 chore: remove DOMWorld definition from externs.d.ts
  src/ExecutionContext.ts
  src/externs.d.ts
Labels: cla: yes

#5773 chore: migrate src/FrameManager to TypeScript
  src/DOMWorld.ts
  src/ExecutionContext.ts
  src/FrameManager.ts
  src/JSHandle.ts
  src/LifecycleWatcher.ts
  src/NetworkManager.js
  src/Page.js
  src/externs.d.ts
  test/utils.js
  utils/doclint/check_public_api/index.js
Labels: cla: yes, typescript-migration

#5771 chore: migrate src/Target to TypeScript
  src/Browser.ts
  src/Page.js
  src/Target.ts
  src/externs.d.ts
Labels: cla: yes, typescript-migration

#5777 Update incorrect link for DeviceDescriptors
  docs/api.md
Labels: cla: yes

#5780 chore: disable flaky setUserAgent test in Firefox
  test/page.spec.js
Labels: cla: yes

#5774 chore: migrate src/NetworkManager to TypeScript
  src/FrameManager.ts
  src/LifecycleWatcher.ts
  src/NetworkManager.ts
  src/Page.js
  src/externs.d.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#5778 docs(contributing): update per recent changes
  CONTRIBUTING.md
Labels: cla: yes

#5782 chore: enable mocha retries
  mocha-config/puppeteer-unit-tests.js
Labels: cla: yes

#5784 chore: fix doclint issues
  CONTRIBUTING.md
  utils/doclint/check_public_api/JSBuilder.js
Labels: cla: yes

#5785 chore: log product + binary on unit test runs
  test/mocha-utils.js
Labels: cla: yes

#5787 chore: turn on Travis retries
  .travis.yml
Labels: cla: yes

#5779 chore: update how we track coverage during unit tests
  .gitignore
  .travis.yml
  mocha-config/coverage-tests.js
  package.json
  test/assert-coverage-test.js
  test/coverage-utils.js
  test/mocha-utils.js
  travis/chromium.sh
Labels: cla: yes

#5775 chore: migrate src/Launcher to TypeScript
  docs/api.md
  src/Launcher.ts
  src/PipeTransport.ts
  src/Puppeteer.js
  src/externs.d.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes, typescript-migration
