Repository puppeteer/puppeteer, pull requests merged in 2020-06, with the labels that each got.

#5954 chore: Defer Windows FF test for longer
  test/headful.spec.js
  test/launcher.spec.js
Labels: cla: yes

#5952 chore: Revert Mitt due to breaking changes
  docs/api.md
  package.json
  src/Browser.ts
  src/BrowserFetcher.ts
  src/Connection.ts
  src/EventEmitter.ts
  src/FrameManager.ts
  src/NetworkManager.ts
  src/Page.ts
  src/WebSocketTransport.ts
  src/WebWorker.ts
  src/api.ts
  src/helper.ts
  src/launcher/BrowserRunner.ts
  tsconfig.json
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#5959 chore: mark version v3.3.0
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#5960 chore: mark version v3.3.0-post
  docs/api.md
  package.json
Labels: cla: yes

#5947 Edited diagram for increased readability on dark backgrounds for #a11y
  docs/api.md
  docs/assets/puppeteerOverview.png
  docs/assets/puppeteerOverview.svg
Labels: cla: yes

#5965 test: check installation with Firefox
  scripts/test-install.sh
Labels: cla: yes

#5967 [WIP] chore: Introduce API Extractor and start generating documentation
  .gitignore
  api-extractor.json
  package.json
  src/Browser.ts
  src/Connection.ts
  src/EmulationManager.ts
  src/Launcher.ts
  src/Page.ts
  src/PipeTransport.ts
  src/Puppeteer.ts
  src/QueryHandler.ts
  src/Target.ts
  src/WebSocketTransport.ts
  src/api-docs-entry.ts
  src/launcher/BrowserRunner.ts
  tsconfig.json
Labels: cla: yes

#5971 feat(new-docs): add TSDoc comments to `Accessibility`
  new-docs/puppeteer.accessibility._constructor_.md
  new-docs/puppeteer.accessibility.md
  new-docs/puppeteer.accessibility.snapshot.md
  new-docs/puppeteer.md
  new-docs/puppeteer.serializedaxnode.autocomplete.md
  new-docs/puppeteer.serializedaxnode.checked.md
  new-docs/puppeteer.serializedaxnode.children.md
  new-docs/puppeteer.serializedaxnode.description.md
  new-docs/puppeteer.serializedaxnode.disabled.md
  new-docs/puppeteer.serializedaxnode.expanded.md
  new-docs/puppeteer.serializedaxnode.focused.md
  new-docs/puppeteer.serializedaxnode.haspopup.md
  new-docs/puppeteer.serializedaxnode.invalid.md
  new-docs/puppeteer.serializedaxnode.keyshortcuts.md
  new-docs/puppeteer.serializedaxnode.level.md
  new-docs/puppeteer.serializedaxnode.md
  new-docs/puppeteer.serializedaxnode.modal.md
  new-docs/puppeteer.serializedaxnode.multiline.md
  new-docs/puppeteer.serializedaxnode.multiselectable.md
  new-docs/puppeteer.serializedaxnode.name.md
  new-docs/puppeteer.serializedaxnode.orientation.md
  new-docs/puppeteer.serializedaxnode.pressed.md
  new-docs/puppeteer.serializedaxnode.readonly.md
  new-docs/puppeteer.serializedaxnode.required.md
  new-docs/puppeteer.serializedaxnode.role.md
  new-docs/puppeteer.serializedaxnode.roledescription.md
  new-docs/puppeteer.serializedaxnode.selected.md
  new-docs/puppeteer.serializedaxnode.value.md
  new-docs/puppeteer.serializedaxnode.valuemax.md
  new-docs/puppeteer.serializedaxnode.valuemin.md
  new-docs/puppeteer.serializedaxnode.valuetext.md
  new-docs/puppeteer.snapshotoptions.interestingonly.md
  new-docs/puppeteer.snapshotoptions.md
  new-docs/puppeteer.snapshotoptions.root.md
  src/Accessibility.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes, tsdoc-migration

#5981 feat(new-docs): migrate Dialog documentation to TSDoc
  new-docs/puppeteer.dialog._constructor_.md
  new-docs/puppeteer.dialog.accept.md
  new-docs/puppeteer.dialog.defaultvalue.md
  new-docs/puppeteer.dialog.dismiss.md
  new-docs/puppeteer.dialog.md
  new-docs/puppeteer.dialog.message.md
  new-docs/puppeteer.dialog.type.md
  new-docs/puppeteer.dialogtype.md
  new-docs/puppeteer.md
  src/Dialog.ts
  src/Page.ts
Labels: cla: yes, tsdoc-migration

#5982 chore: clean `lib` when running tsc
  package.json
Labels: cla: yes

#5990 Remove prefers-color-scheme "no-preference".
  docs/api.md
  test/emulation.spec.js
Labels: cla: yes

#5994 chore: ensure new-docs are up to date
  .travis.yml
  package.json
Labels: cla: yes

#6000 Add documentation to Mouse class for copy-pasting text
  docs/api.md
Labels: cla: yes

#6001 docs(new): Start documenting the `Page` class
  new-docs/puppeteer.md
  new-docs/puppeteer.page._constructor_.md
  new-docs/puppeteer.page._go.md
  new-docs/puppeteer.page._onlogentryadded.md
  new-docs/puppeteer.page._ontargetcrashed.md
  new-docs/puppeteer.page._screenshottask.md
  new-docs/puppeteer.page.create.md
  new-docs/puppeteer.page.md
  new-docs/puppeteer.pageemittedevents.md
  src/Page.ts
Labels: cla: yes, do not merge yet, tsdoc-migration

#6006 docs: replace @return with @returns
  examples/custom-event.js
  install.js
  new-docs/puppeteer.browser.waitfortarget.md
  new-docs/puppeteer.browserfetcher._getfolderpath.md
  new-docs/puppeteer.browserfetcher.download.md
  new-docs/puppeteer.connection.createsession.md
  new-docs/puppeteer.connection.session.md
  new-docs/puppeteer.elementhandle.boxmodel.md
  new-docs/puppeteer.elementhandle.md
  new-docs/puppeteer.httprequest.failure.md
  new-docs/puppeteer.httprequest.md
  src/Browser.ts
  src/BrowserFetcher.ts
  src/Connection.ts
  src/DOMWorld.ts
  src/ExecutionContext.ts
  src/HTTPRequest.ts
  src/JSHandle.ts
  src/Launcher.ts
  src/LifecycleWatcher.ts
  test/golden-utils.js
  test/requestinterception.spec.js
  test/utils.js
  utils/check_availability.js
  utils/doclint/Message.js
  utils/doclint/Source.js
  utils/doclint/check_public_api/Documentation.js
  utils/doclint/check_public_api/JSBuilder.js
  utils/doclint/check_public_api/MDBuilder.js
  utils/doclint/check_public_api/index.js
  utils/doclint/preprocessor/index.js
  utils/fetch_devices.js
  utils/testserver/index.js
Labels: cla: yes

#6007 chore: move `index.js` into `src`
  index.js
  src/index.ts
Labels: cla: yes

#6009 Fix docs linter
  docs/api.md
Labels: cla: yes

#6010 Fix npm test command
  package.json
Labels: cla: yes

#6017 fix(connection): separate send/receive debug logging
  src/Connection.ts
Labels: cla: yes

#5979 chore: migrate away from Node's EventEmitter
  docs/api.md
  new-docs/puppeteer.eventemitter.addlistener.md
  new-docs/puppeteer.eventemitter.emit.md
  new-docs/puppeteer.eventemitter.listenercount.md
  new-docs/puppeteer.eventemitter.md
  new-docs/puppeteer.eventemitter.off.md
  new-docs/puppeteer.eventemitter.on.md
  new-docs/puppeteer.eventemitter.once.md
  new-docs/puppeteer.eventemitter.removealllisteners.md
  new-docs/puppeteer.eventemitter.removelistener.md
  new-docs/puppeteer.md
  new-docs/puppeteer.page.md
  package.json
  src/Browser.ts
  src/BrowserFetcher.ts
  src/Connection.ts
  src/EventEmitter.ts
  src/FrameManager.ts
  src/NetworkManager.ts
  src/Page.ts
  src/WebSocketTransport.ts
  src/WebWorker.ts
  src/api-docs-entry.ts
  src/api.ts
  src/helper.ts
  src/launcher/BrowserRunner.ts
  test/EventEmitter.spec.js
  test/page.spec.js
  tsconfig.json
  utils/doclint/check_public_api/index.js
Labels: breaking change, cla: yes

#6011 Fix childprocess killing when the parent process SIGINTs
  mocha-config/base.js
  src/launcher/BrowserRunner.ts
  test/mocha-utils.js
Labels: cla: yes

#6018 chore: mark version 4.0.0
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#6019 chore: mark v4.0.0-post
  docs/api.md
  package.json
Labels: cla: yes

#6022 chore: update references to branch names
  CONTRIBUTING.md
  README.md
  docs/api.md
  docs/troubleshooting.md
  experimental/puppeteer-firefox/package.json
  src/launcher/BrowserRunner.ts
  utils/apply_next_version.js
  utils/doclint/preprocessor/preprocessor.spec.js
  utils/testserver/package.json
Labels: cla: yes

#6021 chore: move `assert` into its own module
  src/Browser.ts
  src/BrowserFetcher.ts
  src/Connection.ts
  src/Coverage.ts
  src/DOMWorld.ts
  src/Dialog.ts
  src/ExecutionContext.ts
  src/FileChooser.ts
  src/FrameManager.ts
  src/HTTPRequest.ts
  src/Input.ts
  src/JSHandle.ts
  src/Launcher.ts
  src/LifecycleWatcher.ts
  src/NetworkManager.ts
  src/Page.ts
  src/Tracing.ts
  src/assert.ts
  src/helper.ts
  src/launcher/BrowserRunner.ts
Labels: cla: yes

#6024 chore: bump version to v4.0.0-post
  docs/api.md
  package.json
Labels: cla: yes

#6028 chore: create new debug module
  src/BrowserFetcher.ts
  src/Connection.ts
  src/Debug.ts
  src/helper.ts
  src/launcher/BrowserRunner.ts
Labels: cla: yes

#6034 chore: add dependency chart generation as script
  .gitignore
  package.json
Labels: cla: yes

#6029 feat(new-docs): add TSDoc comments to `WebWorker`
  new-docs/puppeteer.md
  new-docs/puppeteer.webworker._constructor_.md
  new-docs/puppeteer.webworker.evaluate.md
  new-docs/puppeteer.webworker.evaluatehandle.md
  new-docs/puppeteer.webworker.executioncontext.md
  new-docs/puppeteer.webworker.md
  new-docs/puppeteer.webworker.url.md
  src/WebWorker.ts
Labels: cla: yes

#6038 fix: `page.goto` options type should be optional
  new-docs/puppeteer.frame.goto.md
  new-docs/puppeteer.page.goto.md
  src/FrameManager.ts
  src/Page.ts
Labels: cla: yes

#6041 chore: create `node` directory for Node-only files
  src/Browser.ts
  src/Puppeteer.ts
  src/api-docs-entry.ts
  src/api.ts
  src/node/BrowserFetcher.ts
  src/node/BrowserRunner.ts
  src/node/LaunchOptions.ts
  src/node/Launcher.ts
  src/node/PipeTransport.ts
  utils/doclint/cli.js
Labels: cla: yes

#6039 chore: fix dependency chart generation
  package.json
Labels: cla: yes

#6042 chore: create `common` directory
  DeviceDescriptors.js
  Errors.js
  src/api-docs-entry.ts
  src/api.ts
  src/common/Accessibility.ts
  src/common/Browser.ts
  src/common/Connection.ts
  src/common/ConnectionTransport.ts
  src/common/ConsoleMessage.ts
  src/common/Coverage.ts
  src/common/DOMWorld.ts
  src/common/Debug.ts
  src/common/DeviceDescriptors.ts
  src/common/Dialog.ts
  src/common/EmulationManager.ts
  src/common/Errors.ts
  src/common/EventEmitter.ts
  src/common/Events.ts
  src/common/ExecutionContext.ts
  src/common/FileChooser.ts
  src/common/FrameManager.ts
  src/common/HTTPRequest.ts
  src/common/HTTPResponse.ts
  src/common/Input.ts
  src/common/JSHandle.ts
  src/common/LifecycleWatcher.ts
  src/common/NetworkManager.ts
  src/common/Page.ts
  src/common/Puppeteer.ts
  src/common/PuppeteerViewport.ts
  src/common/QueryHandler.ts
  src/common/SecurityDetails.ts
  src/common/Target.ts
  src/common/TimeoutSettings.ts
  src/common/Tracing.ts
  src/common/USKeyboardLayout.ts
  src/common/WebSocketTransport.ts
  src/common/WebWorker.ts
  src/common/assert.ts
  src/common/helper.ts
  src/index.ts
  src/node/BrowserFetcher.ts
  src/node/BrowserRunner.ts
  src/node/LaunchOptions.ts
  src/node/Launcher.ts
  src/node/PipeTransport.ts
  test/EventEmitter.spec.js
  test/coverage-utils.js
  test/launcher.spec.js
  utils/doclint/cli.js
Labels: cla: yes

#5997 chore: upgrade to Mocha v8
  mocha-config/puppeteer-unit-tests.js
  package.json
  test/coverage-utils.js
  test/mocha-utils.js
Labels: cla: yes

#6052 chore: exclude api.ts from dependency graph
  package.json
Labels: cla: yes

#6049 chore: move `index.js` into `src` and TS-ify
  index.js
  install.js
  package.json
  src/index.ts
  src/initialize.ts
Labels: cla: yes

#6043 chore: remove top level errors and DeviceDescriptors
  DeviceDescriptors.js
  Errors.js
  docs/api.md
  examples/screenshot-fullpage.js
  package.json
  test/launcher.spec.js
Labels: cla: yes

#6053 docs(new): migrate SecurityDetails docs to TSDoc
  new-docs/puppeteer.accessibility.snapshot.md
  new-docs/puppeteer.md
  new-docs/puppeteer.securitydetails._constructor_.md
  new-docs/puppeteer.securitydetails.issuer.md
  new-docs/puppeteer.securitydetails.md
  new-docs/puppeteer.securitydetails.protocol.md
  new-docs/puppeteer.securitydetails.subjectalternativenames.md
  new-docs/puppeteer.securitydetails.subjectname.md
  new-docs/puppeteer.securitydetails.validfrom.md
  new-docs/puppeteer.securitydetails.validto.md
  src/common/Accessibility.ts
  src/common/SecurityDetails.ts
Labels: cla: yes, tsdoc-migration

#6055 chore: enforce a max line length on comments
  .eslintrc.js
  new-docs/puppeteer.webworker.evaluatehandle.md
  new-docs/puppeteer.webworker.md
  src/api-docs-entry.ts
  src/api.ts
  src/common/Accessibility.ts
  src/common/Debug.ts
  src/common/Dialog.ts
  src/common/HTTPRequest.ts
  src/common/JSHandle.ts
  src/common/NetworkManager.ts
  src/common/Page.ts
  src/common/WebWorker.ts
  src/initialize.ts
  src/node/BrowserRunner.ts
  test/coverage-utils.js
  test/launcher.spec.js
Labels: cla: yes, tsdoc-migration

#6059 docs: fix broken link to USKeyboardLayout file
  docs/api.md
Labels: cla: yes

#6063 chore: pin TSDoc related dependencies
  new-docs/puppeteer.browser.md
  new-docs/puppeteer.browsercontext.md
  new-docs/puppeteer.cdpsession.md
  new-docs/puppeteer.connection.md
  new-docs/puppeteer.elementhandle.md
  new-docs/puppeteer.eventemitter.md
  new-docs/puppeteer.framemanager.md
  new-docs/puppeteer.page.md
  new-docs/puppeteer.timeouterror.md
  new-docs/puppeteer.webworker.md
  package.json
Labels: cla: yes

#6062 docs(new): migrate TimeoutError to TSDoc
  new-docs/puppeteer.md
  new-docs/puppeteer.timeouterror.md
  src/common/Errors.ts
Labels: cla: yes, tsdoc-migration

#6064 docs(new): migrate CDPSession to TSDoc
  new-docs/puppeteer.cdpsession._callbacks.md
  new-docs/puppeteer.cdpsession._connection.md
  new-docs/puppeteer.cdpsession._constructor_.md
  new-docs/puppeteer.cdpsession._onclosed.md
  new-docs/puppeteer.cdpsession._onmessage.md
  new-docs/puppeteer.cdpsession._sessionid.md
  new-docs/puppeteer.cdpsession._targettype.md
  new-docs/puppeteer.cdpsession.detach.md
  new-docs/puppeteer.cdpsession.md
  new-docs/puppeteer.md
  src/common/Connection.ts
Labels: cla: yes

#6065 docs(new): migrate ConsoleMessage docs to TSDoc
  new-docs/puppeteer.consolemessage._constructor_.md
  new-docs/puppeteer.consolemessage.args.md
  new-docs/puppeteer.consolemessage.location.md
  new-docs/puppeteer.consolemessage.md
  new-docs/puppeteer.consolemessage.text.md
  new-docs/puppeteer.consolemessage.type.md
  new-docs/puppeteer.consolemessagelocation.columnnumber.md
  new-docs/puppeteer.consolemessagelocation.linenumber.md
  new-docs/puppeteer.consolemessagelocation.md
  new-docs/puppeteer.consolemessagelocation.url.md
  new-docs/puppeteer.consolemessagetype.md
  new-docs/puppeteer.md
  src/common/ConsoleMessage.ts
  src/common/Page.ts
Labels: cla: yes

#6067 docs(new): migrate Target to TSDoc
  new-docs/puppeteer.target._browsercontext.md
  new-docs/puppeteer.target._closedcallback.md
  new-docs/puppeteer.target._constructor_.md
  new-docs/puppeteer.target._defaultviewport.md
  new-docs/puppeteer.target._ignorehttpserrors.md
  new-docs/puppeteer.target._initializedcallback.md
  new-docs/puppeteer.target._initializedpromise.md
  new-docs/puppeteer.target._isclosedpromise.md
  new-docs/puppeteer.target._isinitialized.md
  new-docs/puppeteer.target._pagepromise.md
  new-docs/puppeteer.target._sessionfactory.md
  new-docs/puppeteer.target._targetid.md
  new-docs/puppeteer.target._targetinfo.md
  new-docs/puppeteer.target._targetinfochanged.md
  new-docs/puppeteer.target._workerpromise.md
  new-docs/puppeteer.target.browser.md
  new-docs/puppeteer.target.createcdpsession.md
  new-docs/puppeteer.target.md
  new-docs/puppeteer.target.opener.md
  new-docs/puppeteer.target.page.md
  new-docs/puppeteer.target.type.md
  new-docs/puppeteer.target.worker.md
  src/common/Target.ts
Labels: cla: yes

#6076 Fix broken link to DeviceDescriptors.ts
  docs/api.md
Labels: cla: yes

#6070 docs(new): migrate Browser docs to TSDoc
  new-docs/puppeteer.browser._closecallback.md
  new-docs/puppeteer.browser._connection.md
  new-docs/puppeteer.browser._constructor_.md
  new-docs/puppeteer.browser._contexts.md
  new-docs/puppeteer.browser._createpageincontext.md
  new-docs/puppeteer.browser._defaultcontext.md
  new-docs/puppeteer.browser._defaultviewport.md
  new-docs/puppeteer.browser._disposecontext.md
  new-docs/puppeteer.browser._getversion.md
  new-docs/puppeteer.browser._ignorehttpserrors.md
  new-docs/puppeteer.browser._process.md
  new-docs/puppeteer.browser._targetcreated.md
  new-docs/puppeteer.browser._targetdestroyed.md
  new-docs/puppeteer.browser._targetinfochanged.md
  new-docs/puppeteer.browser._targets.md
  new-docs/puppeteer.browser.browsercontexts.md
  new-docs/puppeteer.browser.close.md
  new-docs/puppeteer.browser.create.md
  new-docs/puppeteer.browser.createincognitobrowsercontext.md
  new-docs/puppeteer.browser.defaultbrowsercontext.md
  new-docs/puppeteer.browser.disconnect.md
  new-docs/puppeteer.browser.isconnected.md
  new-docs/puppeteer.browser.md
  new-docs/puppeteer.browser.newpage.md
  new-docs/puppeteer.browser.pages.md
  new-docs/puppeteer.browser.process.md
  new-docs/puppeteer.browser.target.md
  new-docs/puppeteer.browser.targets.md
  new-docs/puppeteer.browser.useragent.md
  new-docs/puppeteer.browser.version.md
  new-docs/puppeteer.browser.waitfortarget.md
  new-docs/puppeteer.browser.wsendpoint.md
  new-docs/puppeteer.md
  new-docs/puppeteer.waitfortargetoptions.md
  new-docs/puppeteer.waitfortargetoptions.timeout.md
  src/common/Browser.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes, tsdoc-migration

#5985 docs: Fix effect -> affect typos
  docs/api.md
Labels: cla: yes

#6081 chore: fix ESLint violation and lessen rule strictness
  .eslintrc.js
  new-docs/puppeteer.browsercontext.waitfortarget.md
  new-docs/puppeteer.browserfetcher.download.md
  new-docs/puppeteer.coverage.startcsscoverage.md
  new-docs/puppeteer.coverage.startjscoverage.md
  new-docs/puppeteer.elementhandle.click.md
  new-docs/puppeteer.frame.click.md
  new-docs/puppeteer.frame.waitfornavigation.md
  new-docs/puppeteer.frame.waitforselector.md
  new-docs/puppeteer.frame.waitforxpath.md
  new-docs/puppeteer.keyboard.type.md
  new-docs/puppeteer.md
  new-docs/puppeteer.metrics.documents.md
  new-docs/puppeteer.metrics.frames.md
  new-docs/puppeteer.metrics.jseventlisteners.md
  new-docs/puppeteer.metrics.jsheaptotalsize.md
  new-docs/puppeteer.metrics.jsheapusedsize.md
  new-docs/puppeteer.metrics.layoutcount.md
  new-docs/puppeteer.metrics.layoutduration.md
  new-docs/puppeteer.metrics.md
  new-docs/puppeteer.metrics.nodes.md
  new-docs/puppeteer.metrics.recalcstylecount.md
  new-docs/puppeteer.metrics.recalcstyleduration.md
  new-docs/puppeteer.metrics.scriptduration.md
  new-docs/puppeteer.metrics.taskduration.md
  new-docs/puppeteer.metrics.timestamp.md
  new-docs/puppeteer.page.goback.md
  new-docs/puppeteer.page.goforward.md
  new-docs/puppeteer.page.metrics.md
  new-docs/puppeteer.page.setcontent.md
  new-docs/puppeteer.page.waitforfunction.md
  new-docs/puppeteer.puppeteer.defaultargs.md
  package.json
  src/api.ts
  test/coverage-utils.js
  test/emulation.spec.ts
  test/navigation.spec.ts
Labels: cla: yes

#6080 chore: declare `toBeGolden` to TypeScript
  test/coverage.spec.ts
  test/emulation.spec.ts
  test/mocha-utils.ts
  test/requestinterception.spec.ts
  test/screenshot.spec.ts
Labels: cla: yes

#6079 chore: avoid disabling prettier
  src/common/ConsoleMessage.ts
Labels: cla: yes

#6084 feat(api): remove `emulateMedia` method
  docs/api.md
  src/initialize.ts
  test/emulation.spec.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#6078 docs(new): add TSDoc comments to BrowserFetcher
  new-docs/puppeteer.browserfetcher._constructor_.md
  new-docs/puppeteer.browserfetcher._getfolderpath.md
  new-docs/puppeteer.browserfetcher.candownload.md
  new-docs/puppeteer.browserfetcher.download.md
  new-docs/puppeteer.browserfetcher.host.md
  new-docs/puppeteer.browserfetcher.localrevisions.md
  new-docs/puppeteer.browserfetcher.md
  new-docs/puppeteer.browserfetcher.platform.md
  new-docs/puppeteer.browserfetcher.product.md
  new-docs/puppeteer.browserfetcher.remove.md
  new-docs/puppeteer.browserfetcher.revisioninfo.md
  new-docs/puppeteer.md
  src/node/BrowserFetcher.ts
Labels: cla: yes, tsdoc-migration

#6087 docs(new): adds TSDoc for Touchscreen class
  new-docs/puppeteer.md
  new-docs/puppeteer.touchscreen._constructor_.md
  new-docs/puppeteer.touchscreen.md
  new-docs/puppeteer.touchscreen.tap.md
  src/common/Input.ts
Labels: cla: yes

#6090 chore: tidy up TODO from TS tests migration
  test/jshandle.spec.ts
Labels: cla: yes

#6092 docs(new): Adds TSDoc to FileChooser
  new-docs/puppeteer.filechooser._constructor_.md
  new-docs/puppeteer.filechooser.accept.md
  new-docs/puppeteer.filechooser.cancel.md
  new-docs/puppeteer.filechooser.ismultiple.md
  new-docs/puppeteer.filechooser.md
  new-docs/puppeteer.md
  src/common/FileChooser.ts
Labels: cla: yes

#6088 docs(new): Adds TSDoc to Tracing class
  new-docs/puppeteer.md
  new-docs/puppeteer.tracing._constructor_.md
  new-docs/puppeteer.tracing.md
  new-docs/puppeteer.tracing.start.md
  new-docs/puppeteer.tracing.stop.md
  src/common/Tracing.ts
Labels: cla: yes

#6032 docs(new): add TSDoc comments to Puppeteer
  new-docs/puppeteer.md
  new-docs/puppeteer.puppeteer.__experimental_clearqueryhandlers.md
  new-docs/puppeteer.puppeteer.__experimental_customqueryhandlers.md
  new-docs/puppeteer.puppeteer.__experimental_registercustomqueryhandler.md
  new-docs/puppeteer.puppeteer.__experimental_unregistercustomqueryhandler.md
  new-docs/puppeteer.puppeteer._constructor_.md
  new-docs/puppeteer.puppeteer._launcher.md
  new-docs/puppeteer.puppeteer._productname.md
  new-docs/puppeteer.puppeteer.connect.md
  new-docs/puppeteer.puppeteer.createbrowserfetcher.md
  new-docs/puppeteer.puppeteer.defaultargs.md
  new-docs/puppeteer.puppeteer.devices.md
  new-docs/puppeteer.puppeteer.errors.md
  new-docs/puppeteer.puppeteer.executablepath.md
  new-docs/puppeteer.puppeteer.launch.md
  new-docs/puppeteer.puppeteer.md
  new-docs/puppeteer.puppeteer.product.md
  src/common/Puppeteer.ts
Labels: cla: yes

#6097 Remove hard coded `?hl=en` from docs
  docs/troubleshooting.md
Labels: cla: yes

#6054 chore(agnostic): migrate DOMWorld
  src/common/DOMWorld.ts
  src/common/Debug.ts
  src/environment.ts
Labels: cla: yes

#6085 docs(new): migrate HTTPResponse docs to TSDoc
  new-docs/puppeteer.httpresponse._constructor_.md
  new-docs/puppeteer.httpresponse._resolvebody.md
  new-docs/puppeteer.httpresponse.buffer.md
  new-docs/puppeteer.httpresponse.frame.md
  new-docs/puppeteer.httpresponse.fromcache.md
  new-docs/puppeteer.httpresponse.fromserviceworker.md
  new-docs/puppeteer.httpresponse.headers.md
  new-docs/puppeteer.httpresponse.json.md
  new-docs/puppeteer.httpresponse.md
  new-docs/puppeteer.httpresponse.ok.md
  new-docs/puppeteer.httpresponse.remoteaddress.md
  new-docs/puppeteer.httpresponse.request.md
  new-docs/puppeteer.httpresponse.securitydetails.md
  new-docs/puppeteer.httpresponse.status.md
  new-docs/puppeteer.httpresponse.statustext.md
  new-docs/puppeteer.httpresponse.text.md
  new-docs/puppeteer.httpresponse.url.md
  new-docs/puppeteer.md
  new-docs/puppeteer.remoteaddress.ip.md
  new-docs/puppeteer.remoteaddress.md
  new-docs/puppeteer.remoteaddress.port.md
  src/common/HTTPResponse.ts
Labels: cla: yes, tsdoc-migration

#6099 feat(new-docs): add TSDoc comments to Keyboard
  new-docs/puppeteer.keyboard._client.md
  new-docs/puppeteer.keyboard._constructor_.md
  new-docs/puppeteer.keyboard._modifiers.md
  new-docs/puppeteer.keyboard._pressedkeys.md
  new-docs/puppeteer.keyboard.down.md
  new-docs/puppeteer.keyboard.md
  new-docs/puppeteer.keyboard.press.md
  new-docs/puppeteer.keyboard.sendcharacter.md
  new-docs/puppeteer.keyboard.type.md
  new-docs/puppeteer.keyboard.up.md
  new-docs/puppeteer.md
  src/common/Input.ts
Labels: cla: yes

#6096 feat(types): improve typing of `.evaluate()`
  .eslintrc.js
  README.md
  new-docs/puppeteer.elementhandle.__eval.md
  new-docs/puppeteer.elementhandle._eval.md
  new-docs/puppeteer.evaluatefn.md
  new-docs/puppeteer.evaluatefnreturntype.md
  new-docs/puppeteer.frame.__eval.md
  new-docs/puppeteer.frame._eval.md
  new-docs/puppeteer.jshandle.evaluate.md
  new-docs/puppeteer.jsonarray.md
  new-docs/puppeteer.jsonobject.md
  new-docs/puppeteer.md
  new-docs/puppeteer.page.__eval.md
  new-docs/puppeteer.page._eval.md
  new-docs/puppeteer.serializable.md
  new-docs/puppeteer.serializableorjshandle.md
  src/api-docs-entry.ts
  src/common/DOMWorld.ts
  src/common/EvalTypes.ts
  src/common/FrameManager.ts
  src/common/JSHandle.ts
  src/common/Page.ts
Labels: cla: yes

#6095 chore(agnostic): ship CJS and ESM builds
  api-extractor.json
  cjs-entry.js
  package.json
  scripts/test-install.sh
  src/common/Puppeteer.ts
  src/index.ts
  src/initialize.ts
  tsconfig-esm.json
  tsconfig.json
  utils/doclint/cli.js
Labels: cla: yes

#6102 docs(new): migrate JSHandle docs to TSDoc
  new-docs/puppeteer.boxmodel.md
  new-docs/puppeteer.elementhandle._.md
  new-docs/puppeteer.elementhandle.__.md
  new-docs/puppeteer.elementhandle.md
  new-docs/puppeteer.jshandle.aselement.md
  new-docs/puppeteer.jshandle.dispose.md
  new-docs/puppeteer.jshandle.evaluatehandle.md
  new-docs/puppeteer.jshandle.executioncontext.md
  new-docs/puppeteer.jshandle.getproperty.md
  new-docs/puppeteer.jshandle.jsonvalue.md
  new-docs/puppeteer.jshandle.md
  new-docs/puppeteer.jshandle.tostring.md
  new-docs/puppeteer.md
  src/common/JSHandle.ts
Labels: cla: yes, tsdoc-migration

#6104 docs(new): migrate Page.ts to TSDoc (part 0 / 2)
  docs/api.md
  new-docs/puppeteer.geolocationoptions.accuracy.md
  new-docs/puppeteer.geolocationoptions.latitude.md
  new-docs/puppeteer.geolocationoptions.longitude.md
  new-docs/puppeteer.geolocationoptions.md
  new-docs/puppeteer.md
  new-docs/puppeteer.metrics.md
  new-docs/puppeteer.page._.md
  new-docs/puppeteer.page.browser.md
  new-docs/puppeteer.page.browsercontext.md
  new-docs/puppeteer.page.frames.md
  new-docs/puppeteer.page.goback.md
  new-docs/puppeteer.page.goforward.md
  new-docs/puppeteer.page.goto.md
  new-docs/puppeteer.page.isjavascriptenabled.md
  new-docs/puppeteer.page.mainframe.md
  new-docs/puppeteer.page.md
  new-docs/puppeteer.page.reload.md
  new-docs/puppeteer.page.setcontent.md
  new-docs/puppeteer.page.setdefaultnavigationtimeout.md
  new-docs/puppeteer.page.setdefaulttimeout.md
  new-docs/puppeteer.page.setgeolocation.md
  new-docs/puppeteer.page.setofflinemode.md
  new-docs/puppeteer.page.setrequestinterception.md
  new-docs/puppeteer.page.target.md
  new-docs/puppeteer.page.waitforfilechooser.md
  new-docs/puppeteer.page.waitfornavigation.md
  new-docs/puppeteer.page.workers.md
  new-docs/puppeteer.waitforoptions.md
  new-docs/puppeteer.waitforoptions.timeout.md
  new-docs/puppeteer.waitforoptions.waituntil.md
  new-docs/puppeteer.waittimeoutoptions.md
  new-docs/puppeteer.waittimeoutoptions.timeout.md
  src/common/Page.ts
Labels: cla: yes, tsdoc-migration

#6113 docs(api.md): fix broken links in api.md
  docs/api.md
Labels: cla: yes

#6129 chore: fix Firefox install checker
  scripts/test-install.sh
Labels: cla: yes

#6128 docs(api): fix overview diagram for pptr.dev
  docs/api.md
Labels: cla: yes

#6126 chore(docs): mark JSHandle properties as internal
  new-docs/puppeteer.jshandle._client.md
  new-docs/puppeteer.jshandle._constructor_.md
  new-docs/puppeteer.jshandle._context.md
  new-docs/puppeteer.jshandle._disposed.md
  new-docs/puppeteer.jshandle._remoteobject.md
  new-docs/puppeteer.jshandle.md
  src/common/JSHandle.ts
Labels: cla: yes
