Repository puppeteer/puppeteer, pull requests merged in 2020-07, with the labels that each got.

#6133 chore: update Windows skipped tests.
  test/headful.spec.ts
  test/launcher.spec.ts
  test/mocha-utils.ts
Labels: cla: yes

#6130 feat(types): add (and fix) `evaluateHandle` types
  docs/api.md
  new-docs/puppeteer.evaluatehandlefn.md
  new-docs/puppeteer.executioncontext.evaluatehandle.md
  new-docs/puppeteer.frame.evaluatehandle.md
  new-docs/puppeteer.frame.waitfor.md
  new-docs/puppeteer.frame.waitforfunction.md
  new-docs/puppeteer.jshandle.evaluatehandle.md
  new-docs/puppeteer.md
  new-docs/puppeteer.page.evaluatehandle.md
  new-docs/puppeteer.page.waitfor.md
  new-docs/puppeteer.page.waitforfunction.md
  new-docs/puppeteer.webworker.evaluatehandle.md
  src/common/DOMWorld.ts
  src/common/EvalTypes.ts
  src/common/ExecutionContext.ts
  src/common/FrameManager.ts
  src/common/JSHandle.ts
  src/common/Page.ts
  src/common/WebWorker.ts
  test/elementhandle.spec.ts
  test/jshandle.spec.ts
Labels: cla: yes

#6135 feat(types): add types for `$eval`
  new-docs/puppeteer.elementhandle._eval.md
  new-docs/puppeteer.elementhandle.aselement.md
  new-docs/puppeteer.elementhandle.md
  new-docs/puppeteer.frame._eval.md
  new-docs/puppeteer.jshandle.evaluatehandle.md
  new-docs/puppeteer.md
  new-docs/puppeteer.page._eval.md
  new-docs/puppeteer.page.md
  new-docs/puppeteer.unwrapelementhandle.md
  new-docs/puppeteer.wrapelementhandle.md
  src/common/DOMWorld.ts
  src/common/EvalTypes.ts
  src/common/FrameManager.ts
  src/common/JSHandle.ts
  src/common/Page.ts
  test/click.spec.ts
  test/input.spec.ts
  test/keyboard.spec.ts
  test/page.spec.ts
  test/queryselector.spec.ts
  test/requestinterception.spec.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#6140 chore: add typecheck command
  package.json
Labels: cla: yes

#6143 chore: mark v5.0.0
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#6144 chore: mark v5.0.0-post
  docs/api.md
  package.json
Labels: cla: yes

#6145 chore(docs): fix more documentation warnings
  new-docs/puppeteer.credentials.md
  new-docs/puppeteer.credentials.password.md
  new-docs/puppeteer.credentials.username.md
  new-docs/puppeteer.frame._childframes.md
  new-docs/puppeteer.frame._client.md
  new-docs/puppeteer.frame._constructor_.md
  new-docs/puppeteer.frame._detached.md
  new-docs/puppeteer.frame._framemanager.md
  new-docs/puppeteer.frame._id.md
  new-docs/puppeteer.frame._lifecycleevents.md
  new-docs/puppeteer.frame._loaderid.md
  new-docs/puppeteer.frame._mainworld.md
  new-docs/puppeteer.frame._name.md
  new-docs/puppeteer.frame._parentframe.md
  new-docs/puppeteer.frame._secondaryworld.md
  new-docs/puppeteer.frame._url.md
  new-docs/puppeteer.frame.md
  new-docs/puppeteer.frame.waitforselector.md
  new-docs/puppeteer.frame.waitforxpath.md
  new-docs/puppeteer.framemanager._client.md
  new-docs/puppeteer.framemanager._constructor_.md
  new-docs/puppeteer.framemanager._contextidtocontext.md
  new-docs/puppeteer.framemanager._ensureisolatedworld.md
  new-docs/puppeteer.framemanager._frames.md
  new-docs/puppeteer.framemanager._handleframetree.md
  new-docs/puppeteer.framemanager._isolatedworlds.md
  new-docs/puppeteer.framemanager._mainframe.md
  new-docs/puppeteer.framemanager._networkmanager.md
  new-docs/puppeteer.framemanager._onexecutioncontextcreated.md
  new-docs/puppeteer.framemanager._onexecutioncontextdestroyed.md
  new-docs/puppeteer.framemanager._onexecutioncontextscleared.md
  new-docs/puppeteer.framemanager._onframeattached.md
  new-docs/puppeteer.framemanager._onframedetached.md
  new-docs/puppeteer.framemanager._onframenavigated.md
  new-docs/puppeteer.framemanager._onframenavigatedwithindocument.md
  new-docs/puppeteer.framemanager._onframestoppedloading.md
  new-docs/puppeteer.framemanager._onlifecycleevent.md
  new-docs/puppeteer.framemanager._page.md
  new-docs/puppeteer.framemanager._removeframesrecursively.md
  new-docs/puppeteer.framemanager._timeoutsettings.md
  new-docs/puppeteer.framemanager.executioncontextbyid.md
  new-docs/puppeteer.framemanager.frame.md
  new-docs/puppeteer.framemanager.frames.md
  new-docs/puppeteer.framemanager.initialize.md
  new-docs/puppeteer.framemanager.mainframe.md
  new-docs/puppeteer.framemanager.md
  new-docs/puppeteer.framemanager.navigateframe.md
  new-docs/puppeteer.framemanager.networkmanager.md
  new-docs/puppeteer.framemanager.page.md
  new-docs/puppeteer.framemanager.waitforframenavigation.md
  new-docs/puppeteer.md
  new-docs/puppeteer.page.authenticate.md
  new-docs/puppeteer.waitforselectoroptions.hidden.md
  new-docs/puppeteer.waitforselectoroptions.md
  new-docs/puppeteer.waitforselectoroptions.timeout.md
  new-docs/puppeteer.waitforselectoroptions.visible.md
  src/api-docs-entry.ts
  src/common/DOMWorld.ts
  src/common/FrameManager.ts
  src/common/NetworkManager.ts
Labels: cla: yes

#6148 fix: fix isNode variable not properly detecting Node.js environment
  src/environment.ts
Labels: cla: yes

#5288 Fixed sandboxing documentation link
  docs/troubleshooting.md
Labels: cla: yes

#6152 docs: migrating Page.ts to TSDoc
  new-docs/puppeteer.page.__eval.md
  new-docs/puppeteer.page.cookies.md
  new-docs/puppeteer.page.md
  src/common/Page.ts
Labels: cla: yes, tsdoc-migration

#6146 chore(docs): document HTTPRequest with TSDoc
  new-docs/puppeteer.continuerequestoverrides.headers.md
  new-docs/puppeteer.continuerequestoverrides.md
  new-docs/puppeteer.continuerequestoverrides.method.md
  new-docs/puppeteer.continuerequestoverrides.postdata.md
  new-docs/puppeteer.continuerequestoverrides.url.md
  new-docs/puppeteer.errorcode.md
  new-docs/puppeteer.httprequest._constructor_.md
  new-docs/puppeteer.httprequest._failuretext.md
  new-docs/puppeteer.httprequest._frommemorycache.md
  new-docs/puppeteer.httprequest._interceptionid.md
  new-docs/puppeteer.httprequest._redirectchain.md
  new-docs/puppeteer.httprequest._requestid.md
  new-docs/puppeteer.httprequest._response.md
  new-docs/puppeteer.httprequest.abort.md
  new-docs/puppeteer.httprequest.continue.md
  new-docs/puppeteer.httprequest.failure.md
  new-docs/puppeteer.httprequest.frame.md
  new-docs/puppeteer.httprequest.headers.md
  new-docs/puppeteer.httprequest.isnavigationrequest.md
  new-docs/puppeteer.httprequest.md
  new-docs/puppeteer.httprequest.method.md
  new-docs/puppeteer.httprequest.postdata.md
  new-docs/puppeteer.httprequest.redirectchain.md
  new-docs/puppeteer.httprequest.resourcetype.md
  new-docs/puppeteer.httprequest.respond.md
  new-docs/puppeteer.httprequest.response.md
  new-docs/puppeteer.httprequest.url.md
  new-docs/puppeteer.md
  new-docs/puppeteer.responseforrequest.body.md
  new-docs/puppeteer.responseforrequest.contenttype.md
  new-docs/puppeteer.responseforrequest.headers.md
  new-docs/puppeteer.responseforrequest.md
  new-docs/puppeteer.responseforrequest.status.md
  src/common/HTTPRequest.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes, tsdoc-migration

#6139 feat(types): add types for `page.$$eval`
  new-docs/puppeteer.elementhandle.__eval.md
  new-docs/puppeteer.frame.__eval.md
  new-docs/puppeteer.page.__eval.md
  src/common/DOMWorld.ts
  src/common/FrameManager.ts
  src/common/JSHandle.ts
  src/common/Page.ts
  test/queryselector.spec.ts
Labels: cla: yes

#6141 feat: add wheel method to Mouse class
  docs/api.md
  new-docs/puppeteer.md
  new-docs/puppeteer.mouse.md
  new-docs/puppeteer.mouse.wheel.md
  new-docs/puppeteer.mousewheeloptions.deltax.md
  new-docs/puppeteer.mousewheeloptions.deltay.md
  new-docs/puppeteer.mousewheeloptions.md
  src/common/Input.ts
  test/assets/input/wheel.html
  test/mouse.spec.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#6154 chore(docs): migrate & document all Page events
  new-docs/puppeteer.md
  new-docs/puppeteer.page.md
  new-docs/puppeteer.pageemittedevents.md
  src/common/Page.ts
  src/common/Target.ts
Labels: cla: yes, tsdoc-migration

#6165 chore(docs): define events enum for `Browser`
  new-docs/puppeteer.browser.md
  new-docs/puppeteer.browseremittedevents.md
  new-docs/puppeteer.md
  src/common/Browser.ts
Labels: cla: yes

#6166 chore(docs): fix DOMWorld doc warnings
  new-docs/puppeteer.frame.goto.md
  new-docs/puppeteer.frame.setcontent.md
  new-docs/puppeteer.frame.waitfornavigation.md
  new-docs/puppeteer.md
  new-docs/puppeteer.puppeteerlifecycleevent.md
  new-docs/puppeteer.waitforoptions.md
  src/api-docs-entry.ts
  src/common/DOMWorld.ts
  src/common/LifecycleWatcher.ts
  src/common/TimeoutSettings.ts
Labels: cla: yes, tsdoc-migration

#6168 chore(docs): Migrate `BrowserContext` events.
  new-docs/puppeteer.browsercontext.md
  new-docs/puppeteer.browsercontextemittedevents.md
  new-docs/puppeteer.md
  src/common/Browser.ts
Labels: cla: yes, typescript-migration

#6170 Update Puppeteer.ts
  src/common/Puppeteer.ts
Labels: cla: yes

#6174 chore: migrate NetworkManager events
  src/common/Events.ts
  src/common/LifecycleWatcher.ts
  src/common/NetworkManager.ts
  src/common/Page.ts
Labels: cla: yes, tsdoc-migration

#6175 chore(docs): fix incorrect `@returns` on getter
  new-docs/puppeteer.puppeteer.devices.md
  new-docs/puppeteer.puppeteer.errors.md
  src/common/Puppeteer.ts
Labels: cla: yes, tsdoc-migration

#6179 chore: migrate FrameManager events from Events.ts
  src/common/FrameManager.ts
  src/common/LifecycleWatcher.ts
  src/common/Page.ts
Labels: cla: yes, tsdoc-migration

#6180 chore(docs): migrate Connection + CDP event defs
  new-docs/puppeteer.connection._callbacks.md
  new-docs/puppeteer.connection._closed.md
  new-docs/puppeteer.connection._constructor_.md
  new-docs/puppeteer.connection._delay.md
  new-docs/puppeteer.connection._lastid.md
  new-docs/puppeteer.connection._onclose.md
  new-docs/puppeteer.connection._onmessage.md
  new-docs/puppeteer.connection._rawsend.md
  new-docs/puppeteer.connection._sessions.md
  new-docs/puppeteer.connection._transport.md
  new-docs/puppeteer.connection._url.md
  new-docs/puppeteer.connection.createsession.md
  new-docs/puppeteer.connection.dispose.md
  new-docs/puppeteer.connection.fromsession.md
  new-docs/puppeteer.connection.md
  new-docs/puppeteer.connection.send.md
  new-docs/puppeteer.connection.session.md
  new-docs/puppeteer.connection.url.md
  new-docs/puppeteer.md
  src/common/Browser.ts
  src/common/Connection.ts
  src/common/LifecycleWatcher.ts
  src/common/Page.ts
Labels: cla: yes, tsdoc-migration

#6183 chore: forbid importing src/common/Events.ts
  .eslintrc.js
  src/common/LifecycleWatcher.ts
  src/common/Page.ts
Labels: cla: yes, tsdoc-migration

#6186 chore: remove `installAsyncStackHooks` helper
  new-docs/puppeteer.puppeteer._lazylauncher.md
  new-docs/puppeteer.puppeteer.md
  src/api.ts
  src/common/Puppeteer.ts
  src/common/helper.ts
  src/initialize.ts
  test/launcher.spec.ts
  test/page.spec.ts
Labels: cla: yes

#6187 chore: document browser install breakage on Node 14.0.0
  docs/troubleshooting.md
Labels: cla: yes

#6188 chore(docs): document Frame class
  new-docs/puppeteer.frame._.md
  new-docs/puppeteer.frame.__.md
  new-docs/puppeteer.frame.__eval.md
  new-docs/puppeteer.frame._detach.md
  new-docs/puppeteer.frame._eval.md
  new-docs/puppeteer.frame._navigated.md
  new-docs/puppeteer.frame._navigatedwithindocument.md
  new-docs/puppeteer.frame._onlifecycleevent.md
  new-docs/puppeteer.frame._onloadingstopped.md
  new-docs/puppeteer.frame._x.md
  new-docs/puppeteer.frame.addscripttag.md
  new-docs/puppeteer.frame.addstyletag.md
  new-docs/puppeteer.frame.childframes.md
  new-docs/puppeteer.frame.click.md
  new-docs/puppeteer.frame.content.md
  new-docs/puppeteer.frame.evaluate.md
  new-docs/puppeteer.frame.evaluatehandle.md
  new-docs/puppeteer.frame.executioncontext.md
  new-docs/puppeteer.frame.focus.md
  new-docs/puppeteer.frame.goto.md
  new-docs/puppeteer.frame.hover.md
  new-docs/puppeteer.frame.isdetached.md
  new-docs/puppeteer.frame.md
  new-docs/puppeteer.frame.name.md
  new-docs/puppeteer.frame.parentframe.md
  new-docs/puppeteer.frame.select.md
  new-docs/puppeteer.frame.setcontent.md
  new-docs/puppeteer.frame.tap.md
  new-docs/puppeteer.frame.title.md
  new-docs/puppeteer.frame.type.md
  new-docs/puppeteer.frame.url.md
  new-docs/puppeteer.frame.waitfor.md
  new-docs/puppeteer.frame.waitforfunction.md
  new-docs/puppeteer.frame.waitfornavigation.md
  new-docs/puppeteer.frame.waitforselector.md
  new-docs/puppeteer.frame.waitforxpath.md
  new-docs/puppeteer.frameaddscripttagoptions.content.md
  new-docs/puppeteer.frameaddscripttagoptions.md
  new-docs/puppeteer.frameaddscripttagoptions.path.md
  new-docs/puppeteer.frameaddscripttagoptions.type.md
  new-docs/puppeteer.frameaddscripttagoptions.url.md
  new-docs/puppeteer.frameaddstyletagoptions.content.md
  new-docs/puppeteer.frameaddstyletagoptions.md
  new-docs/puppeteer.frameaddstyletagoptions.path.md
  new-docs/puppeteer.frameaddstyletagoptions.url.md
  new-docs/puppeteer.framewaitforfunctionoptions.md
  new-docs/puppeteer.framewaitforfunctionoptions.polling.md
  new-docs/puppeteer.framewaitforfunctionoptions.timeout.md
  new-docs/puppeteer.md
  new-docs/puppeteer.page.evaluate.md
  src/common/FrameManager.ts
  src/common/Page.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes, tsdoc-migration

#6181 chore(docs): tidy Puppeteer class docs
  new-docs/puppeteer.md
  new-docs/puppeteer.puppeteer.__productname.md
  new-docs/puppeteer.puppeteer._changedproduct.md
  new-docs/puppeteer.puppeteer._ispuppeteercore.md
  new-docs/puppeteer.puppeteer._preferredrevision.md
  new-docs/puppeteer.puppeteer.md
  new-docs/puppeteer.puppeteer.product.md
  src/common/Puppeteer.ts
Labels: cla: yes, tsdoc-migration

#6191 chore: remove src/api.ts
  .travis.yml
  package.json
  src/api.ts
  test/coverage-utils.js
  utils/doclint/check_public_api/index.js
  utils/doclint/check_public_api/test/.gitignore
  utils/doclint/check_public_api/test/check-duplicates/doc.md
  utils/doclint/check_public_api/test/check-duplicates/foo.js
  utils/doclint/check_public_api/test/check-duplicates/result.txt
  utils/doclint/check_public_api/test/check-returns/doc.md
  utils/doclint/check_public_api/test/check-returns/foo.js
  utils/doclint/check_public_api/test/check-returns/result.txt
  utils/doclint/check_public_api/test/check-sorting/Events.js
  utils/doclint/check_public_api/test/check-sorting/doc.md
  utils/doclint/check_public_api/test/check-sorting/foo.js
  utils/doclint/check_public_api/test/check-sorting/result.txt
  utils/doclint/check_public_api/test/diff-arguments/doc.md
  utils/doclint/check_public_api/test/diff-arguments/foo.js
  utils/doclint/check_public_api/test/diff-arguments/result.txt
  utils/doclint/check_public_api/test/diff-classes/doc.md
  utils/doclint/check_public_api/test/diff-classes/foo.js
  utils/doclint/check_public_api/test/diff-classes/other.js
  utils/doclint/check_public_api/test/diff-classes/result.txt
  utils/doclint/check_public_api/test/diff-events/Events.js
  utils/doclint/check_public_api/test/diff-events/doc.md
  utils/doclint/check_public_api/test/diff-events/foo.js
  utils/doclint/check_public_api/test/diff-events/result.txt
  utils/doclint/check_public_api/test/diff-methods/doc.md
  utils/doclint/check_public_api/test/diff-methods/foo.js
  utils/doclint/check_public_api/test/diff-methods/result.txt
  utils/doclint/check_public_api/test/diff-properties/doc.md
  utils/doclint/check_public_api/test/diff-properties/foo.js
  utils/doclint/check_public_api/test/diff-properties/result.txt
  utils/doclint/check_public_api/test/js-builder-common/Events.js
  utils/doclint/check_public_api/test/js-builder-common/foo.js
  utils/doclint/check_public_api/test/js-builder-common/result.txt
  utils/doclint/check_public_api/test/js-builder-inheritance/Events.js
  utils/doclint/check_public_api/test/js-builder-inheritance/foo.js
  utils/doclint/check_public_api/test/js-builder-inheritance/result.txt
  utils/doclint/check_public_api/test/md-builder-common/doc.md
  utils/doclint/check_public_api/test/md-builder-common/result.txt
  utils/doclint/check_public_api/test/public-api.spec.js
Labels: cla: yes

#6172 chore: use devtools-protocol package
  .eslintignore
  .travis.yml
  docs/api.md
  new-docs/puppeteer.cdpsession.md
  new-docs/puppeteer.cdpsession.send.md
  new-docs/puppeteer.page.deletecookie.md
  package.json
  scripts/ensure-correct-devtools-protocol-package.ts
  src/common/Accessibility.ts
  src/common/Browser.ts
  src/common/Connection.ts
  src/common/Coverage.ts
  src/common/Dialog.ts
  src/common/EmulationManager.ts
  src/common/ExecutionContext.ts
  src/common/FileChooser.ts
  src/common/FrameManager.ts
  src/common/HTTPRequest.ts
  src/common/HTTPResponse.ts
  src/common/JSHandle.ts
  src/common/NetworkManager.ts
  src/common/Page.ts
  src/common/SecurityDetails.ts
  src/common/Target.ts
  src/common/WebWorker.ts
  src/common/helper.ts
  src/protocol.d.ts
  utils/apply_next_version.js
  utils/doclint/check_public_api/JSBuilder.js
  utils/doclint/check_public_api/index.js
  utils/protocol-types-generator/index.js
Labels: cla: yes, do not merge yet, typescript-migration

#6193 feat(types): improve page.evaluate types
  new-docs/puppeteer.evaluatefn.md
  new-docs/puppeteer.evaluatefnreturntype.md
  new-docs/puppeteer.frame.evaluate.md
  new-docs/puppeteer.jshandle.evaluate.md
  new-docs/puppeteer.md
  new-docs/puppeteer.page.evaluate.md
  new-docs/puppeteer.serializable.md
  new-docs/puppeteer.unwrappromiselike.md
  src/common/DOMWorld.ts
  src/common/EvalTypes.ts
  src/common/FrameManager.ts
  src/common/JSHandle.ts
  src/common/Page.ts
  test/browsercontext.spec.ts
  test/cookies.spec.ts
  test/coverage.spec.ts
  test/elementhandle.spec.ts
  test/emulation.spec.ts
  test/evaluation.spec.ts
  test/frame.spec.ts
  test/input.spec.ts
  test/jshandle.spec.ts
  test/keyboard.spec.ts
  test/mouse.spec.ts
  test/navigation.spec.ts
  test/page.spec.ts
  test/queryselector.spec.ts
  test/requestinterception.spec.ts
  test/screenshot.spec.ts
  test/target.spec.ts
  test/waittask.spec.ts
  test/worker.spec.ts
Labels: cla: yes, typescript-migration

#6201 feat(chromium): roll Chromium to r768783
  package.json
  src/revisions.ts
  test/cookies.spec.ts
  utils/check_availability.js
Labels: cla: yes

#6206 chore: mark version v5.1.0
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#6208 chore: mark version to v5.1.0-post
  docs/api.md
  package.json
Labels: cla: yes

#5354 docs(troubleshooting): drops obsolete dependencies
  docs/troubleshooting.md
Labels: cla: yes

#6209 chore: vendor Mitt & update project structure
  .eslintignore
  .eslintrc.js
  CONTRIBUTING.md
  api-extractor.json
  cjs-entry-core.js
  cjs-entry.js
  install.js
  package.json
  src/common/EventEmitter.ts
  src/tsconfig.cjs.json
  src/tsconfig.esm.json
  test/EventEmitter.spec.ts
  test/coverage-utils.js
  test/elementhandle.spec.ts
  test/keyboard.spec.ts
  test/launcher.spec.ts
  test/mocha-ts-require.js
  test/mocha-utils.ts
  test/mouse.spec.ts
  test/page.spec.ts
  test/target.spec.ts
  test/tsconfig.test.json
  test/worker.spec.ts
  tsconfig.base.json
  tsconfig.json
  utils/doclint/check_public_api/index.js
  utils/doclint/cli.js
  vendor/README.md
  vendor/mitt/README.md
  vendor/mitt/dist/index.d.ts
  vendor/mitt/dist/mitt.es.js
  vendor/mitt/dist/mitt.es.js.map
  vendor/mitt/dist/mitt.js
  vendor/mitt/dist/mitt.js.map
  vendor/mitt/dist/mitt.modern.js
  vendor/mitt/dist/mitt.modern.js.map
  vendor/mitt/dist/mitt.umd.js
  vendor/mitt/dist/mitt.umd.js.map
  vendor/mitt/package.json
  vendor/mitt/src/index.ts
  vendor/tsconfig.cjs.json
  vendor/tsconfig.esm.json
Labels: cla: yes, do not merge yet

#6226 Better describe how to install Firefox Nightly with Puppeteer
  docs/api.md
  src/node/Launcher.ts
Labels: cla: yes

#6218 feat: change QueryHandler to contain QueryOne and QueryAll methods
  src/common/DOMWorld.ts
  src/common/JSHandle.ts
  src/common/QueryHandler.ts
  test/elementhandle.spec.ts
Labels: cla: yes

#6238 chore: mark v5.2.0
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#6240 chore: mark 5.2.0-post
  docs/api.md
  package.json
Labels: cla: yes

#6236 docs(troubleshooting): install libXss in Dockerfile
  docs/troubleshooting.md
Labels: cla: yes

#6228 chore(docs): migrate page.pdf() docs
  new-docs/puppeteer.md
  new-docs/puppeteer.page.md
  new-docs/puppeteer.page.pdf.md
  new-docs/puppeteer.page.queryobjects.md
  new-docs/puppeteer.paperformat.md
  new-docs/puppeteer.pdfmargin.bottom.md
  new-docs/puppeteer.pdfmargin.left.md
  new-docs/puppeteer.pdfmargin.md
  new-docs/puppeteer.pdfmargin.right.md
  new-docs/puppeteer.pdfmargin.top.md
  new-docs/puppeteer.pdfoptions.displayheaderfooter.md
  new-docs/puppeteer.pdfoptions.footertemplate.md
  new-docs/puppeteer.pdfoptions.format.md
  new-docs/puppeteer.pdfoptions.headertemplate.md
  new-docs/puppeteer.pdfoptions.height.md
  new-docs/puppeteer.pdfoptions.landscape.md
  new-docs/puppeteer.pdfoptions.margin.md
  new-docs/puppeteer.pdfoptions.md
  new-docs/puppeteer.pdfoptions.pageranges.md
  new-docs/puppeteer.pdfoptions.path.md
  new-docs/puppeteer.pdfoptions.prefercsspagesize.md
  new-docs/puppeteer.pdfoptions.printbackground.md
  new-docs/puppeteer.pdfoptions.scale.md
  new-docs/puppeteer.pdfoptions.width.md
  new-docs/puppeteer.puppeteer.md
  src/api-docs-entry.ts
  src/common/PDFOptions.ts
  src/common/Page.ts
  src/common/Puppeteer.ts
Labels: cla: yes, tsdoc-migration

#6210 fix: configure debug logging in browser
  src/common/Debug.ts
Labels: cla: yes

#6254 chore: mark v5.2.1
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#6257 chore: mark 5.2.1-post
  docs/api.md
  package.json
Labels: cla: yes

#6231 chore(docs): `page.emulateVisionDeficiency` docs
  new-docs/puppeteer.page.emulatevisiondeficiency.md
  new-docs/puppeteer.page.md
  src/common/Page.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes, tsdoc-migration

#6200 chore: add test runner for testing pptr in a browser
  .eslintignore
  .eslintrc.js
  .travis.yml
  package.json
  test-browser/debug.spec.js
  web-test-runner.config.js
Labels: cla: yes

#6270 fix: handle promise for reading protocol stream of trace
  src/common/Tracing.ts
  test/tracing.spec.ts
Labels: cla: yes

#6276 docs(api): fix typo in elementHandle.evaluateHandle()
  docs/api.md
Labels: cla: yes

#6269 chore: test Connection class in the browser
  test-browser/connection.spec.js
Labels: cla: yes

#6268 feat: page.waitForTimeout
  docs/api.md
  new-docs/puppeteer.frame.md
  new-docs/puppeteer.frame.waitfor.md
  new-docs/puppeteer.frame.waitfortimeout.md
  new-docs/puppeteer.page.md
  new-docs/puppeteer.page.waitfor.md
  new-docs/puppeteer.page.waitfortimeout.md
  package.json
  src/common/FrameManager.ts
  src/common/Page.ts
  test/elementhandle.spec.ts
  test/waittask.spec.ts
Labels: cla: yes

#6287 chore: upgrade Mitt to 2.1
  vendor/README.md
  vendor/mitt/README.md
  vendor/mitt/dist/mitt.es.js
  vendor/mitt/dist/mitt.es.js.map
  vendor/mitt/dist/mitt.js
  vendor/mitt/dist/mitt.js.map
  vendor/mitt/dist/mitt.modern.js
  vendor/mitt/dist/mitt.modern.js.map
  vendor/mitt/dist/mitt.umd.js
  vendor/mitt/dist/mitt.umd.js.map
  vendor/mitt/index.d.ts
  vendor/mitt/package.json
  vendor/mitt/src/index.ts
Labels: cla: yes

#6282 test: assert location value of ConsoleMessage
  test/page.spec.ts
Labels: cla: yes

#6267 docs(troubleshooting.md) fix error in docker guidelines
  docs/troubleshooting.md
Labels: cla: yes
