Repository puppeteer/puppeteer, pull requests merged in 2020-01, with the labels that each got.

#5272 docs(readme): Update link for ndb
  README.md
Labels: cla: yes

#5293 chore: move to GitHub hosting for Juggler binaries
  experimental/puppeteer-firefox/lib/BrowserFetcher.js
  experimental/puppeteer-firefox/package.json
Labels: cla: yes

#5294 chore: mark puppeteer-firefox version v0.5.1
  experimental/puppeteer-firefox/package.json
Labels: cla: yes, firefox

#5289 [WIP] feat(chromium): roll Chromium to r722269
  lib/ExecutionContext.js
  lib/JSHandle.js
  lib/Page.js
  package.json
  test/accessibility.spec.js
  test/chromiumonly.spec.js
Labels: chromium, cla: yes

#5347 chore: mark version v2.1.0
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#5349 chore: bump version to v2.1.0-post
  docs/api.md
  package.json
Labels: cla: yes

#5200 docs(api.md): Adding new example to page.$$eval
  docs/api.md
Labels: cla: yes

#5325 feat: make it possible to run `install.js` script with `puppeteer-core`
  docs/api.md
  install.js
  utils/prepare_puppeteer_core.js
Labels: cla: yes

#5360 Update FAQ with an entry on cross-browser support
  README.md
Labels: cla: yes

#5369 fix(filechooser): quick fix for the headful file chooser
  lib/Page.js
Labels: cla: yes
