Repository puppeteer/puppeteer, pull requests merged in 2021-05, with the labels that each got.

#7182 Disable flaky test on firefox
  test/click.spec.ts
Labels: cla: yes

#7192 feat: add option to filter targets
  docs/api.md
  src/common/Browser.ts
  src/common/BrowserConnector.ts
  test/launcher.spec.ts
Labels: cla: yes

#7201 chore(release): mark v9.1.0
  CHANGELOG.md
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#7202 chore: bump version to v9.1.0-post
  docs/api.md
  package.json
Labels: cla: yes

#7203 fix: make targetFilter synchronous
  docs/api.md
  src/common/Browser.ts
Labels: cla: yes

#7205 chore(release): mark v9.1.1
  CHANGELOG.md
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#7206 chore: bump version to v9.1.1-post
  docs/api.md
  package.json
Labels: cla: yes

#7207 chore: disable flaky test on Firefox
  test/elementhandle.spec.ts
Labels: cla: yes

#7060 fix(requestinterception): fix font loading issue
  src/common/NetworkManager.ts
  test/assets/cached/one-style-font.css
  test/assets/cached/one-style-font.html
  test/requestinterception.spec.ts
Labels: cla: yes

#7105 feat(launcher): add new launcher option `waitForInitialPage`
  docs/api.md
  src/node/LaunchOptions.ts
  src/node/Launcher.ts
  test/launcher.spec.ts
Labels: cla: yes

#6863 feat: expose other sessions from connection
  docs/api.md
  src/common/Connection.ts
  src/common/Page.ts
  test/headful.spec.ts
Labels: cla: yes

#7219 chore: fix typo in WebWorker.ts
  src/common/WebWorker.ts
Labels: cla: yes

#7224 docs: add lowercasing of HTTP headers to documentation
  docs/api.md
Labels: cla: yes

#7226 chore: drop Firefox workaround
  src/common/Connection.ts
Labels: cla: yes

#7228 chore: avoid linting auto-generated Markdown
  package.json
Labels: cla: yes, do not merge yet

#7232 chore: upgrade and pin prettier dependencies
  package.json
  src/common/AriaQueryHandler.ts
  src/common/Browser.ts
  src/common/BrowserConnector.ts
  src/common/Coverage.ts
  src/common/DOMWorld.ts
  src/common/EmulationManager.ts
  src/common/ExecutionContext.ts
  src/common/JSHandle.ts
  src/common/NetworkManager.ts
  src/common/Page.ts
  src/common/QueryHandler.ts
  src/node/BrowserFetcher.ts
  src/node/BrowserRunner.ts
  src/node/Launcher.ts
  src/node/Puppeteer.ts
  test/click.spec.ts
  test/cookies.spec.ts
  test/elementhandle.spec.ts
  test/launcher.spec.ts
  utils/check_availability.js
  utils/doclint/preprocessor/index.js
  utils/fetch_devices.js
Labels: cla: yes

#7230 chore: fix eslint warnings around type defs
  .eslintrc.js
  package.json
  src/common/EventEmitter.ts
  src/common/FileChooser.ts
  src/node/install.ts
  test/cookies.spec.ts
  test/mocha-utils.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#7238 chore: enforce pinned dependencies
  .github/workflows/main.yml
  package.json
  scripts/ensure-pinned-deps.ts
  test/waittask.spec.ts
Labels: cla: yes

#7216 test: remove console.log in unit test
  test/page.spec.ts
Labels: cla: yes

#7200 chore: drop support for Node.js 10
  .github/workflows/main.yml
  tsconfig.base.json
Labels: cla: yes

#7217 feat(requestinterception): remove cacheSafe flag
  docs/api.md
  src/common/NetworkManager.ts
  src/common/Page.ts
  test/requestinterception.spec.ts
Labels: cla: yes

#7256 chore: set `module` to `esnext` in `tsconfig.json`
  tsconfig.base.json
  tsconfig.json
Labels: cla: yes

#7262 fix: modified comment for method product, platform and newPage
  src/common/Browser.ts
  src/node/BrowserFetcher.ts
  tsconfig.json
Labels: cla: yes

#7075 test: reorder describes in JS coverage spec
  test/coverage.spec.ts
Labels: cla: yes

#7271 Close browser in case of test failed with timeout
  test/headful.spec.ts
Labels: cla: yes

#7276 chore: add github-retry to unit tests
  .github/workflows/main.yml
Labels: cla: yes

#7267 chore: improve type inference of evaluate
  scripts/test-ts-definition-files.ts
  src/common/JSHandle.ts
  test-ts-types/js-cjs-import-esm-output/package.json
  test-ts-types/js-esm-import-cjs-output/bad.js
  test-ts-types/js-esm-import-cjs-output/package.json
  test-ts-types/js-esm-import-esm-output/package.json
  test-ts-types/ts-cjs-import-cjs-output/package.json
  test-ts-types/ts-esm-import-cjs-output/package.json
  test-ts-types/ts-esm-import-esm-output/bad.ts
  test-ts-types/ts-esm-import-esm-output/good.ts
  test-ts-types/ts-esm-import-esm-output/package.json
  utils/doclint/check_public_api/index.js
Labels: cla: yes, typescript-migration

#7266 Added comments for some of the methods
  src/common/EventEmitter.ts
  src/common/HTTPRequest.ts
  src/common/JSHandle.ts
  src/common/Page.ts
  src/common/WebWorker.ts
Labels: cla: yes

#7277 test: fix typo in page test
  test/page.spec.ts
Labels: cla: yes

#7288 feat(chromium): roll to Chromium 92.0.4512.0 (r884014)
  docs/api.md
  package.json
  src/common/Accessibility.ts
  src/common/AriaQueryHandler.ts
  src/common/Connection.ts
  src/revisions.ts
  test/CDPSession.spec.ts
  test/accessibility.spec.ts
  test/headful.spec.ts
  versions.js
Labels: cla: yes

#7293 test: move network emulation tests to the emulation spec file
  test/emulation.spec.ts
  test/page.spec.ts
Labels: cla: yes

#7292 test: fix page.browserContext test title
  test/page.spec.ts
Labels: cla: yes

#7296 Npm: Update ws to a non-vulnerable version
  package.json
Labels: cla: yes

#7300 chore: fix puppeteer version in chromium roll
  docs/api.md
  versions.js
Labels: cla: yes

#7299 chore(release): mark v10.0.0
  CHANGELOG.md
  README.md
  docs/api.md
  package.json
  versions.js
Labels: cla: yes

#7302 chore: bump version to v10.0.0-post
  docs/api.md
  package.json
Labels: cla: yes
