Repository puppeteer/puppeteer, pull requests merged in 2021-02, with the labels that each got.

#6799 chore: drop Travis CI config
  .ci/node10/Dockerfile.linux
  .ci/node12/Dockerfile.linux
  .travis.yml
  README.md
Labels: cla: yes

#6800 chore(release): mark v6.0.0
  CHANGELOG.md
  README.md
  docs/api.md
  package.json
  versions.js
Labels: cla: yes

#6802 chore: bump version to v6.0.0-post
  docs/api.md
  package.json
Labels: cla: yes

#6803 chore: fix version number
  docs/api.md
  utils/doclint/cli.js
  versions.js
Labels: cla: yes

#6805 feat: use `captureBeyondViewport` in `Page.captureScreenshot`
  src/common/Page.ts
  test/golden-chromium/screenshot-offscreen-clip-artefacts.png
  test/golden-chromium/screenshot-offscreen-clip.png
  test/golden-firefox/screenshot-offscreen-clip-artefacts.png
  test/screenshot.spec.ts
Labels: cla: yes

#6804 chore(release): mark v7.0.0
  CHANGELOG.md
  README.md
  docs/api.md
  package.json
  versions.js
Labels: cla: yes

#6808 chore: bump version to v7.0.0-post
  docs/api.md
  package.json
Labels: cla: yes

#6811 fix(typescript): ship .d.ts file in npm package
  package.json
Labels: cla: yes

#6812 chore(release): mark v7.0.1
  CHANGELOG.md
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#6814 chore: bump version to 7.0.1-post
  docs/api.md
  package.json
Labels: cla: yes

#6815 fix(launcher): output correct error message for browser
  src/node/Launcher.ts
Labels: cla: yes

#6813 docs(contributing): update example PR link
  CONTRIBUTING.md
Labels: cla: yes

#6821 chore: let actions/checkout determine the branch by itself
  .github/workflows/main.yml
Labels: cla: yes

#6660 Updated proxy-from-env to ^1.1.0
  package.json
Labels: cla: yes

#6826 chore: cleanup remaining Travis references
  docs/troubleshooting.md
  experimental/puppeteer-firefox/.npmignore
  utils/doclint/cli.js
Labels: cla: yes

#6831 docs(contributing): fix typo around test directory link
  CONTRIBUTING.md
Labels: cla: yes

#6809 chore: don't ship tsbuildinfo files in npm package
  package.json
Labels: cla: yes

#6836 fix(domworld): reset bindings when context changes (#6766)
  src/common/DOMWorld.ts
  test/ariaqueryhandler.spec.ts
Labels: cla: yes

#6837 fix: much better TypeScript definitions
  README.md
  api-extractor.json
  cjs-entry.d.ts
  package.json
  scripts/add-default-export-to-types.ts
  src/common/EvalTypes.ts
Labels: cla: yes

#6842 chore(release): mark v7.0.2
  CHANGELOG.md
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#6844 fix: include lib/types.d.ts in files list
  package.json
Labels: cla: yes

#6843 chore: bump version to 7.0.2-post
  docs/api.md
  package.json
Labels: cla: yes

#6828 docs(troubleshooting): update broken Dockerfile link to historical one
  docs/troubleshooting.md
Labels: cla: yes

#6845 chore(release): mark v7.0.3
  CHANGELOG.md
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#6846 chore: bump version to 7.0.3-post
  docs/api.md
  package.json
Labels: cla: yes

#6847 chore(domworld): clear set
  src/common/DOMWorld.ts
Labels: cla: yes

#6848 fix: make publish bot run full build, not just tsc
  package.json
Labels: cla: yes

#6849 chore: fix doclint violations
  package.json
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#6850 chore(release): mark v7.0.4
  CHANGELOG.md
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#6851 chore: mark version 7.0.4-post
  docs/api.md
  package.json
Labels: cla: yes

#6855 fix: wider compat TS types and CI checks to ensure correct type defs
  .eslintignore
  .github/workflows/main.yml
  .github/workflows/publish-on-tag.yml
  .gitignore
  package.json
  scripts/add-default-export-to-types.ts
  scripts/test-ts-definition-files.ts
  src/api-docs-entry.ts
  src/common/NetworkConditions.ts
  test-ts-types/js-cjs-import-cjs-output/bad.js
  test-ts-types/js-cjs-import-cjs-output/good.js
  test-ts-types/js-cjs-import-cjs-output/package.json
  test-ts-types/js-cjs-import-cjs-output/tsconfig.json
  test-ts-types/js-cjs-import-esm-output/bad.js
  test-ts-types/js-cjs-import-esm-output/good.js
  test-ts-types/js-cjs-import-esm-output/package.json
  test-ts-types/js-cjs-import-esm-output/tsconfig.json
  test-ts-types/js-esm-import-cjs-output/bad.js
  test-ts-types/js-esm-import-cjs-output/good.js
  test-ts-types/js-esm-import-cjs-output/package.json
  test-ts-types/js-esm-import-cjs-output/tsconfig.json
  test-ts-types/js-esm-import-esm-output/bad.js
  test-ts-types/js-esm-import-esm-output/good.js
  test-ts-types/js-esm-import-esm-output/package.json
  test-ts-types/js-esm-import-esm-output/tsconfig.json
  test-ts-types/ts-cjs-import-cjs-output/bad.ts
  test-ts-types/ts-cjs-import-cjs-output/good.ts
  test-ts-types/ts-cjs-import-cjs-output/package.json
  test-ts-types/ts-cjs-import-cjs-output/tsconfig.json
  test-ts-types/ts-esm-import-cjs-output/bad.ts
  test-ts-types/ts-esm-import-cjs-output/good.ts
  test-ts-types/ts-esm-import-cjs-output/package.json
  test-ts-types/ts-esm-import-cjs-output/tsconfig.json
  test-ts-types/ts-esm-import-esm-output/bad.ts
  test-ts-types/ts-esm-import-esm-output/good.ts
  test-ts-types/ts-esm-import-esm-output/package.json
  test-ts-types/ts-esm-import-esm-output/tsconfig.json
Labels: cla: yes

#6864 chore: temporarily disable FF tests on CI
  .github/workflows/main.yml
Labels: cla: yes

#6869 fix: expose `ScreenshotOptions` type in type defs
  src/common/Page.ts
Labels: cla: yes, typescript-migration

#6865 fix: jsonValue() type is generic
  src/common/JSHandle.ts
  test/evaluation.spec.ts
  test/jshandle.spec.ts
Labels: cla: yes, typescript-migration

#6860 chore: improve TS automated type tests
  .gitignore
  scripts/test-ts-definition-files.ts
  test-ts-types/js-cjs-import-cjs-output/package.json
  test-ts-types/js-cjs-import-esm-output/package.json
  test-ts-types/js-esm-import-cjs-output/package.json
  test-ts-types/js-esm-import-esm-output/package.json
  test-ts-types/ts-cjs-import-cjs-output/package.json
  test-ts-types/ts-esm-import-cjs-output/package.json
  test-ts-types/ts-esm-import-esm-output/package.json
Labels: cla: yes

#6870 chore: upgrade @web/test-runner and increase timeout
  package.json
  web-test-runner.config.js
Labels: cla: yes

#6868 fix: add favicon test asset
  test/assets/favicon.ico
  test/assets/offscreenbuttons.html
  test/click.spec.ts
Labels: cla: yes

#6857 feat(page): add color-gamut support to Page.emulateMediaFeatures
  docs/api.md
  src/common/Page.ts
  test/emulation.spec.ts
Labels: cla: yes

#6856 fix: expose puppeteer.Permission type
  src/common/Browser.ts
  test/page.spec.ts
  utils/doclint/check_public_api/index.js
Labels: cla: yes

#6879 chore(release): mark v7.1.0
  CHANGELOG.md
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#6880 chore: bump to 7.1.0-post
  docs/api.md
  package.json
Labels: cla: yes

#6881 fix: expose `Viewport` type
  src/api-docs-entry.ts
  src/common/Page.ts
  src/common/PuppeteerViewport.ts
Labels: cla: yes, typescript-migration

#6888 fix: improve TS types for launching browsers
  src/api-docs-entry.ts
  src/common/BrowserConnector.ts
  src/common/Puppeteer.ts
  src/node/LaunchOptions.ts
  src/node/Launcher.ts
  src/node/Puppeteer.ts
Labels: cla: yes, typescript-migration

#6889 chore: upgrade TypeScript to 4.1.5
  package.json
  test/navigation.spec.ts
Labels: cla: yes

#6882 fix: explicit HTTPRequest.resourceType type defs
  src/common/HTTPRequest.ts
Labels: cla: yes, typescript-migration

#6901 fix: move CI npm config out of .npmrc
  .github/workflows/publish-on-tag.yml
  .npmrc
Labels: cla: yes

#6890 docs(readme): page.pdf format using a4
  README.md
Labels: cla: yes

#6861 chore: skip Page.addScriptTag and Frame.waitForSelector specs in Firefox
  .github/workflows/main.yml
Labels: cla: yes

#6896 chore: run unit tests for Firefox on MacOS
  .github/workflows/main.yml
  test/keyboard.spec.ts
Labels: cla: yes

#6911 fix(docs): api doc typo #6903
  docs/api.md
Labels: cla: yes

#6918 Replace erroneous `PUPPETEER_SKIP_DOWNLOAD`
  docs/api.md
Labels: cla: no

#6927 feat(chromium): roll Chromium to r856583
  package.json
  src/revisions.ts
  test/cookies.spec.ts
  test/defaultbrowsercontext.spec.ts
Labels: cla: yes

#6928 chore(release): mark v8.0.0
  CHANGELOG.md
  README.md
  docs/api.md
  package.json
Labels: cla: yes

#6929 chore: bump version to v8.0.0-post
  docs/api.md
  package.json
Labels: cla: yes
