Repository puppeteer/puppeteer, pull requests merged in 2023-10, with the labels that each got.

#11152 feat: merge user-provided --{disable,enable}-features in args
  packages/puppeteer-core/src/node/ChromeLauncher.test.ts
  packages/puppeteer-core/src/node/ChromeLauncher.ts
Labels: feature

#11153 fix: `Page.waitForDevicePrompt` crash
  packages/puppeteer-core/src/cdp/Frame.ts
Labels: bug

#11213 fix: typo in screencast error message
  packages/puppeteer-core/src/api/Page.ts
Labels: automerge

#11212 docs: fix typos in `docs` and `website` folder
  docs/browsers-api/browsers.browserplatform.md
  docs/browsers-api/index.md
  packages/browsers/src/browser-data/types.ts
Labels: automerge
