Repository puppeteer/puppeteer, pull requests merged in 2024-02, with the labels that each got.

#11812 test: disable failing Firefox tests
  test/TestExpectations.json
Labels: full-ci

#11814 test: clean up expectations
  test/TestExpectations.json
Labels: full-ci

#10912 feat!: drop support for node16
  package-lock.json
  packages/browsers/package.json
  packages/ng-schematics/package.json
  packages/puppeteer-core/package.json
  packages/puppeteer-core/src/common/BrowserConnector.ts
  packages/puppeteer-core/src/common/common.ts
  packages/puppeteer-core/src/common/fetch.ts
  packages/puppeteer/package.json
Labels: DO NOT MERGE

#11532 feat!: BiDi cookies
  docs/api/index.md
  docs/api/puppeteer.cookie.md
  docs/api/puppeteer.cookieparam.md
  docs/api/puppeteer.cookiepriority.md
  docs/api/puppeteer.cookiesamesite.md
  docs/api/puppeteer.cookiesourcescheme.md
  docs/api/puppeteer.deletecookiesrequest.md
  docs/api/puppeteer.page.cookies.md
  docs/api/puppeteer.page.deletecookie.md
  docs/api/puppeteer.page.setcookie.md
  packages/puppeteer-core/src/api/Page.ts
  packages/puppeteer-core/src/bidi/Page.ts
  packages/puppeteer-core/src/bidi/core/Connection.ts
  packages/puppeteer-core/src/cdp/Page.ts
  packages/puppeteer-core/src/common/Cookie.ts
  packages/puppeteer-core/src/common/common.ts
  test/TestExpectations.json
  test/src/cookies.spec.ts
  test/src/defaultbrowsercontext.spec.ts
  test/src/mocha-utils.ts
Labels: breaking change, bidi, DO NOT MERGE

#11605 feat!: remove PUPPETEER_DOWNLOAD_PATH in favor of PUPPETEER_CACHE_DIR
  docs/api/puppeteer.configuration.md
  packages/puppeteer-core/src/common/Configuration.ts
  packages/puppeteer-core/src/node/PuppeteerNode.ts
  packages/puppeteer/src/getConfiguration.ts
  packages/puppeteer/src/node/cli.ts
  packages/puppeteer/src/node/install.ts
  test/installation/src/puppeteer.spec.ts
Labels: DO NOT MERGE

#11774 fix!: remove viewport resizing from ElementHandle.screenshot
  packages/puppeteer-core/src/api/ElementHandle.ts
Labels: DO NOT MERGE

#11778 feat!: generate accessible PDFs by default
  docs/api/puppeteer.pdfoptions.md
  packages/puppeteer-core/src/common/PDFOptions.ts
  packages/puppeteer-core/src/common/util.ts
  test/TestExpectations.json
  test/src/page.spec.ts
Labels: DO NOT MERGE

#11782 refactor!: remove `$x` and `waitForXpath`
  docs/api/puppeteer.elementhandle._x.md
  docs/api/puppeteer.elementhandle.md
  docs/api/puppeteer.elementhandle.waitforxpath.md
  docs/api/puppeteer.frame._x.md
  docs/api/puppeteer.frame.md
  docs/api/puppeteer.frame.waitforxpath.md
  docs/api/puppeteer.page._x.md
  docs/api/puppeteer.page.md
  docs/api/puppeteer.page.waitforxpath.md
  packages/puppeteer-core/src/api/ElementHandle.ts
  packages/puppeteer-core/src/api/Frame.ts
  packages/puppeteer-core/src/api/Page.ts
  test/TestExpectations.json
  test/src/elementhandle.spec.ts
  test/src/queryselector.spec.ts
  test/src/waittask.spec.ts
  website/versioned_docs/version-21.11.0/api/puppeteer.frame.waitfortimeout.md
  website/versioned_docs/version-21.11.0/api/puppeteer.page.waitfortimeout.md
Labels: DO NOT MERGE

#11787 refactor!: remove devices in favor of KnownDevices
  docs/api/index.md
  docs/api/puppeteer.devices.md
  packages/puppeteer-core/src/common/Device.ts
Labels: DO NOT MERGE

#11788 refactor!: remove InterceptResolutionStrategy
  docs/api/index.md
  docs/api/puppeteer.interceptresolutionstrategy.md
  packages/puppeteer-core/src/api/HTTPRequest.ts
Labels: DO NOT MERGE

#11790 fix!: make console warn level compatible with WebDriver BiDi
  docs/api/puppeteer.consolemessagetype.md
  packages/puppeteer-core/src/bidi/Page.ts
  packages/puppeteer-core/src/cdp/Page.ts
  packages/puppeteer-core/src/cdp/WebWorker.ts
  packages/puppeteer-core/src/common/ConsoleMessage.ts
  test/TestExpectations.json
  test/src/page.spec.ts
Labels: DO NOT MERGE

#11803 refactor!: remove duplicate type names
  docs/guides/locators.md
  packages/puppeteer-core/src/api/Browser.ts
  packages/puppeteer-core/src/api/BrowserContext.ts
  packages/puppeteer-core/src/api/Page.ts
  packages/puppeteer-core/src/api/locators/locators.ts
Labels: DO NOT MERGE

#11805 refactor!: use ReadableStreams
  docs/api/puppeteer.page.createpdfstream.md
  packages/puppeteer-core/src/api/Page.ts
  packages/puppeteer-core/src/bidi/Page.ts
  packages/puppeteer-core/src/cdp/Page.ts
  packages/puppeteer-core/src/common/util.ts
  test/src/page.spec.ts
Labels: DO NOT MERGE

#11806 refactor!: remove networkConditions in favor of PredefinedNetworkConditions
  docs/api/index.md
  docs/api/puppeteer.networkconditions.md
  packages/puppeteer-core/src/cdp/PredefinedNetworkConditions.ts
Labels: DO NOT MERGE

#11815 refactor!: enable the new-headless mode by default
  .github/workflows/canary.yml
  .github/workflows/ci.yml
  .github/workflows/deflake.yml
  .vscode/launch.template.json
  README.md
  docs/api/puppeteer.browserlaunchargumentoptions.md
  docs/index.md
  package.json
  packages/puppeteer-core/src/common/PDFOptions.ts
  packages/puppeteer-core/src/node/ChromeLauncher.ts
  packages/puppeteer-core/src/node/LaunchOptions.ts
  packages/puppeteer-core/src/node/ProductLauncher.ts
  test/TestExpectations.json
  test/TestSuites.json
  test/src/fixtures.spec.ts
  test/src/launcher.spec.ts
  test/src/mocha-utils.ts
  test/src/oopif.spec.ts
  website/versioned_docs/version-21.11.0/guides/chrome-extensions.md
Labels: full-ci, DO NOT MERGE

#11825 test: replace usages of webkit-scrollbar with scrollbar-width
  test/TestExpectations.json
  test/assets/frames/nested-frames.html
  test/assets/grid.html
  test/src/screenshot.spec.ts
Labels: full-ci

#11874 test: update expectations for user context tests with Firefox
  test/TestExpectations.json
Labels: full-ci

#11867 test: update expectations for aborted request test
  test/TestExpectations.json
Labels: automerge

#11836 refactor: adopt the rest of `bidi/core`
  packages/puppeteer-core/src/bidi/Browser.ts
  packages/puppeteer-core/src/bidi/BrowserContext.ts
  packages/puppeteer-core/src/bidi/BrowsingContext.ts
  packages/puppeteer-core/src/bidi/CDPSession.ts
  packages/puppeteer-core/src/bidi/Connection.ts
  packages/puppeteer-core/src/bidi/Dialog.ts
  packages/puppeteer-core/src/bidi/ElementHandle.ts
  packages/puppeteer-core/src/bidi/EmulationManager.ts
  packages/puppeteer-core/src/bidi/ExposedFunction.ts
  packages/puppeteer-core/src/bidi/Frame.ts
  packages/puppeteer-core/src/bidi/HTTPRequest.ts
  packages/puppeteer-core/src/bidi/HTTPResponse.ts
  packages/puppeteer-core/src/bidi/Input.ts
  packages/puppeteer-core/src/bidi/JSHandle.ts
  packages/puppeteer-core/src/bidi/NetworkManager.ts
  packages/puppeteer-core/src/bidi/Page.ts
  packages/puppeteer-core/src/bidi/Realm.ts
  packages/puppeteer-core/src/bidi/Sandbox.ts
  packages/puppeteer-core/src/bidi/Target.ts
  packages/puppeteer-core/src/bidi/bidi.ts
  packages/puppeteer-core/src/bidi/lifecycle.ts
  packages/puppeteer-core/src/bidi/util.ts
  packages/puppeteer-core/third_party/rxjs/rxjs.ts
  test/TestExpectations.json
  test/src/ariaqueryhandler.spec.ts
  test/src/evaluation.spec.ts
  test/src/launcher.spec.ts
  test/src/oopif.spec.ts
  test/src/page.spec.ts
  test/src/waittask.spec.ts
Labels: full-ci

#11869 test: enable skipped tests
  test/TestExpectations.json
Labels: full-ci

#11932 test: remove redundant expectations
  test/TestExpectations.json
  test/assets/frames/frame.html
  test/src/elementhandle.spec.ts
  tools/sort-test-expectations.mjs
Labels: full-ci

#11950 test: fix test on Windows
  packages/browsers/test/src/chrome/install.spec.ts
Labels: full-ci

#11951 fix: implement a fallback to download URLs provided by dashboard
  packages/browsers/src/install.ts
  packages/browsers/test/src/chrome/install.spec.ts
  packages/browsers/test/src/firefox/install.spec.ts
Labels: full-ci

#11947 feat: support local aliases when launching a browser
  docs/browsers-api/browsers.installedbrowser.md
  docs/browsers-api/browsers.installedbrowser.readmetadata.md
  docs/browsers-api/browsers.installedbrowser.writemetadata.md
  docs/browsers-api/browsers.installoptions.md
  packages/browsers/src/CLI.ts
  packages/browsers/src/Cache.ts
  packages/browsers/src/install.ts
  packages/browsers/test/src/Cache.spec.ts
  packages/puppeteer/src/node/install.ts
Labels: full-ci

#11975 build: fix windows build
  packages/puppeteer-core/Herebyfile.mjs
Labels: full-ci

#11986 chore: update devcontainer.json to Node 18
  .devcontainer/devcontainer.json
Labels: automerge

#12023 test: update expectations
  test/TestExpectations.json
Labels: full-ci

#12018 fix(webdriver): wait for response if the response has not completed once navigation has finished
  packages/puppeteer-core/src/bidi/Frame.ts
Labels: full-ci
