Repository puppeteer/puppeteer, pull requests merged in 2024-08, with the labels that each got.

#12710 refactor!: replace dynamic imports with static dependency injection
  docs/guides/running-puppeteer-in-extensions.md
  docs/guides/running-puppeteer-in-the-browser.md
  examples/puppeteer-in-browser/rollup.config.mjs
  examples/puppeteer-in-extension/rollup.config.mjs
  packages/puppeteer-core/src/api/Frame.ts
  packages/puppeteer-core/src/api/Page.ts
  packages/puppeteer-core/src/bidi/ElementHandle.ts
  packages/puppeteer-core/src/cdp/ElementHandle.ts
  packages/puppeteer-core/src/common/util.ts
  packages/puppeteer-core/src/environment.ts
  packages/puppeteer-core/src/puppeteer-core.ts
Labels: Stale

#12734 docs: update webdriver page
  docs/webdriver-bidi.md
Labels: DO NOT MERGE

#12756 feat!: rename ignoreHttpsErrors to acceptInsecureCerts
  docs/api/puppeteer.browserconnectoptions.md
  packages/puppeteer-core/src/bidi/Browser.ts
  packages/puppeteer-core/src/bidi/BrowserConnector.ts
  packages/puppeteer-core/src/cdp/Browser.ts
  packages/puppeteer-core/src/cdp/BrowserConnector.ts
  packages/puppeteer-core/src/common/ConnectOptions.ts
  packages/puppeteer-core/src/node/BrowserLauncher.ts
  test/TestExpectations.json
  test/src/acceptInsecureCerts.spec.ts
  test/src/cdp/bfcache.spec.ts
  test/src/cookies.spec.ts
  test/src/device-request-prompt.spec.ts
  test/src/launcher.spec.ts
  test/src/network.spec.ts
Labels: DO NOT MERGE

#12792 refactor!: remove support for NPM configuration
  docs/guides/configuration.md
  packages/puppeteer/src/getConfiguration.ts
  website/versioned_docs/version-22.15.0/api/puppeteer.product.md
  website/versioned_docs/version-22.15.0/api/puppeteer.productlauncher.defaultargs.md
  website/versioned_docs/version-22.15.0/api/puppeteer.productlauncher.executablepath.md
  website/versioned_docs/version-22.15.0/api/puppeteer.productlauncher.launch.md
  website/versioned_docs/version-22.15.0/api/puppeteer.productlauncher.md
Labels: DO NOT MERGE

#12796 refactor: remove code for getting Firefox version from `latest`
  packages/puppeteer-core/src/node/BrowserLauncher.ts
  packages/puppeteer-core/src/node/FirefoxLauncher.ts
  packages/puppeteer-core/src/node/PuppeteerNode.ts
Labels: DO NOT MERGE

#12824 refactor!: remove deprecated functions for CustomQueryHandler
  docs/api/index.md
  docs/api/puppeteer.clearcustomqueryhandlers.md
  docs/api/puppeteer.customqueryhandlernames.md
  docs/api/puppeteer.puppeteer.registercustomqueryhandler.md
  docs/api/puppeteer.registercustomqueryhandler.md
  docs/api/puppeteer.unregistercustomqueryhandler.md
  packages/puppeteer-core/src/common/CustomQueryHandler.ts
  packages/puppeteer-core/src/common/Puppeteer.ts
  packages/puppeteer-core/src/index-browser.ts
  test/src/elementhandle.spec.ts
Labels: DO NOT MERGE

#12795 feat!: support multiple browser downloads for Puppeteer
  .github/workflows/ci.yml
  docs/api/index.md
  docs/api/puppeteer.chromeheadlessshellsettings.md
  docs/api/puppeteer.chromesettings.md
  docs/api/puppeteer.configuration.md
  docs/api/puppeteer.firefoxsettings.md
  docs/guides/configuration.md
  packages/puppeteer-core/src/common/Configuration.ts
  packages/puppeteer-core/src/node/BrowserLauncher.ts
  packages/puppeteer-core/src/node/PuppeteerNode.ts
  packages/puppeteer/install.mjs
  packages/puppeteer/src/getConfiguration.ts
  packages/puppeteer/src/node/cli.ts
  packages/puppeteer/src/node/install.ts
  puppeteer.config.cjs
  test/installation/assets/puppeteer/cdp.js
  test/installation/assets/puppeteer/configuration/.puppeteerrc-browserVersion.cjs
  test/installation/src/puppeteer-configuration.spec.ts
  test/installation/src/puppeteer-firefox.spec.ts
  test/installation/src/puppeteer.spec.ts
Labels: DO NOT MERGE

#12342 test: add a test for a service worker with ignoreHTTPSErrors
  test/src/acceptInsecureCerts.spec.ts
Labels: Stale

#12496 docs: add Google Analytics with consent banner to pptr.dev
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
  website/src/theme/Root.js
Labels: automerge

#12830 refactor!: remove isIncognito
  docs/api/index.md
  docs/api/puppeteer.browsercontext.isincognito.md
  docs/api/puppeteer.browsercontext.md
  packages/puppeteer-core/src/api/BrowserContext.ts
  packages/puppeteer-core/src/bidi/BrowserContext.ts
  packages/puppeteer-core/src/cdp/BrowserContext.ts
  test/src/browsercontext.spec.ts
  test/src/network.spec.ts
Labels: full-ci, DO NOT MERGE

#12940 chore: update deps and pipe errors
  .github/workflows/ci.yml
  package-lock.json
  packages/ng-schematics/package.json
  packages/ng-schematics/tools/projects.mjs
  packages/ng-schematics/tools/smoke.mjs
Labels: full-ci

#12942 ci: update caches to include all browsers
  .github/workflows/ci.yml
  .github/workflows/clear-caches.yml
  .github/workflows/deflake.yml
Labels: full-ci

#12950 feat: improve type inference for selectors by adopting "typed-query-selector"
  docs/api/puppeteer.nodefor.md
  package-lock.json
  packages/puppeteer-core/package.json
  packages/puppeteer-core/src/common/types.ts
  packages/puppeteer/package.json
  test-d/NodeFor.test-d.ts
Labels: automerge

#12980 ci: add cache to job
  .github/workflows/ci.yml
  packages/browsers/tools/downloadTestBrowsers.mjs
  packages/ng-schematics/tools/projects.mjs
  packages/ng-schematics/tools/smoke.mjs
  packages/testserver/src/index.ts
Labels: full-ci
