Repository puppeteer/puppeteer, pull requests merged in 2024-09, with the labels that each got.

#12846 test: Sync expectations for Bug 1882803
  test/TestExpectations.json
Labels: firefox, Stale, m130

#12850 test: Sync expectations for Bug 1903060
  test/TestExpectations.json
Labels: firefox, m130

#13128 build: fix win build
  packages/puppeteer-core/rollup.config.mjs
Labels: full-ci

#13147 chore(deps): bump chromium-bidi to 0.8.0
  package-lock.json
  packages/puppeteer-core/package.json
  packages/puppeteer/package.json
Labels: full-ci
