Repository puppeteer/puppeteer, pull requests merged in 2024-05, with the labels that each got.

#12374 fix: don't start dbus service during build in Dockerfile
  docker/Dockerfile
Labels: automerge

#12371 test: puppeteer.connect with `using` disconnects the browser
  package.json
  packages/puppeteer-core/src/api/Browser.ts
  packages/testserver/src/index.ts
  test/src/browser.spec.ts
  test/src/browsercontext.spec.ts
  test/src/cdp/devtools.spec.ts
  test/src/chromiumonly.spec.ts
  test/src/fixtures.spec.ts
  test/src/launcher.spec.ts
  test/src/oopif.spec.ts
Labels: full-ci

#12349 fix: deprecate CDP for Firefox
  packages/puppeteer-core/src/node/ProductLauncher.ts
Labels: DO NOT MERGE

#12377 fix: remove --disable-field-trial-config
  packages/puppeteer-core/src/node/ChromeLauncher.ts
  test/TestExpectations.json
Labels: full-ci

#12381 fix: disable IsolateSandboxedIframes trial to prevent flakiness
  packages/puppeteer-core/src/node/ChromeLauncher.ts
  test/TestExpectations.json
Labels: full-ci

#12393 ci: fix devtools
  .github/workflows/devtools.yml
Labels: devtools

#12398 refactor: move binding installation into the execution context
  packages/puppeteer-core/src/cdp/ExecutionContext.ts
  packages/puppeteer-core/src/cdp/IsolatedWorld.ts
Labels: devtools

#12400 refactor: simplify worlds handling
  packages/puppeteer-core/src/cdp/Frame.ts
  packages/puppeteer-core/src/cdp/FrameManager.ts
  packages/puppeteer-core/src/cdp/IsolatedWorld.ts
Labels: devtools, full-ci

#12406 refactor: replace deferred with rxjs
  packages/puppeteer-core/src/cdp/IsolatedWorld.ts
Labels: devtools, full-ci

#12407 refactor: move console event handling
  packages/puppeteer-core/src/cdp/ExecutionContext.ts
  packages/puppeteer-core/src/cdp/Frame.ts
  packages/puppeteer-core/src/cdp/FrameManagerEvents.ts
  packages/puppeteer-core/src/cdp/IsolatedWorld.ts
  packages/puppeteer-core/src/cdp/Page.ts
  packages/puppeteer-core/src/cdp/WebWorker.ts
  test/src/launcher.spec.ts
  test/src/worker.spec.ts
Labels: devtools, full-ci

#12411 ci: use npm i in devtools.yml
  .github/workflows/devtools.yml
Labels: devtools

#12438 fix(webdriver): prefer globalThis over window to make it work in Firefox
  packages/puppeteer-core/src/injected/ARIAQuerySelector.ts
  test/TestExpectations.json
Labels: full-ci

#12441 ci: add icacls calls to windows CI
  .github/workflows/canary.yml
  .github/workflows/ci.yml
  docs/troubleshooting.md
Labels: full-ci

#12478 test: disable flaky installation test on macos-13
  test/installation/assets/puppeteer/puppeteer-in-extension.js
  test/installation/src/puppeteer.spec.ts
Labels: full-ci

#12203 fix: providing null to page.authenticate should disable authentication
  docs/api/puppeteer.page.authenticate.md
  packages/puppeteer-core/src/api/Page.ts
  packages/puppeteer-core/src/cdp/NetworkManager.ts
  packages/puppeteer-core/src/cdp/Page.ts
  test/src/network.spec.ts
Labels: full-ci, m125

#12483 test: Update expectations for firefox support of continueRequest
  packages/puppeteer-core/src/api/HTTPRequest.ts
  test/TestExpectations.json
  test/src/requestinterception.spec.ts
Labels: automerge
